### ISSUE TITLE
Error when trying to assign GeoLocate values in paleo database

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#102]
I uploaded a spreadsheet into a newly created invert paleo, cleared out all locality data from one record then changed the state, added a county, and changed the locality name of another row.  I clicked to geolocate that row, selected a point, but when the Geolocate window closed, the geolocate data was not populated and the error below appeared in the error log
Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.WorkbenchTemplateMappingItem.workbenchDataItems, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.PersistentSet.add(PersistentSet.java:189)
	at edu.ku.brc.specify.datamodel.WorkbenchRow.setData(WorkbenchRow.java:847)
	at edu.ku.brc.specify.datamodel.WorkbenchRow.setData(WorkbenchRow.java:790)
	at edu.ku.brc.specify.tasks.subpane.wb.GridTableModel.setValueAt(GridTableModel.java:303)
	at javax.swing.JTable.setValueAt(Unknown Source)
	at org.jdesktop.swingx.JXTable.setValueAt(JXTable.java:1441)
	at javax.swing.JTable.editingStopped(Unknown Source)
	at edu.ku.brc.ui.tmanfe.SpreadSheet.editingStopped(SpreadSheet.java:556)
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(Unknown Source)
	at javax.swing.DefaultCellEditor.stopCellEditing(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$GridCellEditor.stopCellEditing(WorkbenchPaneSS.java:5565)
	at javax.swing.plaf.basic.BasicTableUI$Actions.actionPerformed(Unknown Source)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JTable.processKeyBinding(Unknown Source)
	at edu.ku.brc.ui.tmanfe.SpreadSheet.processKeyBinding(SpreadSheet.java:835)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]
The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]
Couldn't find the ViewDef for formtable definition name[Collectors]
Couldn't find the ViewDef for formtable definition name[Collectors]Couldn't find the ViewDef for formtable definition name[Collectors]
Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.WorkbenchTemplateMappingItem.workbenchDataItems, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.PersistentSet.add(PersistentSet.java:189)
	at edu.ku.brc.specify.datamodel.WorkbenchRow.setData(WorkbenchRow.java:847)
	at edu.ku.brc.specify.datamodel.WorkbenchRow.setData(WorkbenchRow.java:790)
	at edu.ku.brc.specify.datamodel.WorkbenchRow.set(WorkbenchRow.java:1228)
	at edu.ku.brc.services.geolocate.prototype.GeoCoordGeoLocateProvider$4.run(GeoCoordGeoLocateProvider.java:263)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at edu.ku.brc.ui.UIHelper.centerAndShow(UIHelper.java:478)
	at edu.ku.brc.ui.UIHelper.centerAndShow(UIHelper.java:487)
	at edu.ku.brc.services.geolocate.prototype.GeoCoordGeoLocateProvider.processGeoRefData(GeoCoordGeoLocateProvider.java:91)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.doGeoRef(WorkbenchPaneSS.java:3355)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$14.actionPerformed(WorkbenchPaneSS.java:717)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tlammer** [comment]
I put a backup of the database I was using, with the data set I was using in the WorkBench, in \\rfs.home.ku.edu\groups\BI\Specify\Specify6\Databases\Databases for Programmers

**Comment by yvonneekanim** [comment]
Geolocate populates lat/long fields in wb with no errors
