### ISSUE TITLE
Exception when a query box get's focused

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1040]
Whenever a Query box field get's focused, an exception occurs and the next field get's focussed instead

Video of this happening (I pressed "Tab" key only once, but the focussed field moved twice):

https://user-images.githubusercontent.com/40512816/129371802-720d7fa9-ec3b-45aa-8a37-3540506e4907.mp4

Exception:
```yaml
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: failed to access class sun.awt.CausedFocusEvent from class edu.ku.brc.af.ui.db.TextFieldWithQuery$3 (sun.awt.CausedFocusEvent is in module java.desktop of loader 'bootstrap'; edu.ku.brc.af.ui.db.TextFieldWithQuery$3 is in unnamed module of loader 'app')
	at edu.ku.brc.af.ui.db.TextFieldWithQuery$3.focusGained(TextFieldWithQuery.java:290)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:228)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.Component.processFocusEvent(Component.java:6524)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1050)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:674)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


```

**Comment by maxxxxxdlp** [comment]
Replicated with Amazon Corretto 11. Not reproducible with Amazon Corretto 8

**Comment by maxxxxxdlp** [comment]
This seems to also cause focus issues in other places:
My accession number format is `YEAR-AA-###`. The `YEAR-AA` part is required. In Amazon Corretto 8 whenever I fill out the required part, the focus moves to the `###` part automatically. When using Amazon Corretto 11, this does not happen. The above-mentioned exception happens instead.
Exception happens when a form get's focussed too
