### ISSUE TITLE
Gift preparation count's upper bound does not take unavailable items into account

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1042]
1. Create a CO with a prep count of 4
2. Create a Loan for that CO with a loan preparation count of 2
3. Create a Gift for that CO with a gift preparation count of 4 <-- only 2 are available, but we are allowed to use 4
4. Then, when I try to open a Loan Preparation created in step 2, I get this exception:
```yaml
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:161)
	at edu.ku.brc.af.ui.forms.validation.ValSpinner.setRange(ValSpinner.java:128)
	at edu.ku.brc.specify.datamodel.busrules.LoanPreparationBusRules.afterFillForm(LoanPreparationBusRules.java:275)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5455)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4843)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1173)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.setData(ViewBasedDisplayPanel.java:339)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.setData(ViewBasedDisplayDialog.java:494)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1145)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1031)
	at edu.ku.brc.af.ui.forms.TableViewObj$7.mouseClicked(TableViewObj.java:835)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ok

```

**Comment by maxxxxxdlp** [comment]
After this, the "Save" and "Accept" buttons on every form are disabled until Specify is restarted

I am also unable reopen that Loan for editing due to a similar exception:
```yaml
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:161)
	at edu.ku.brc.af.ui.forms.validation.ValSpinner.setRange(ValSpinner.java:128)
	at edu.ku.brc.specify.datamodel.busrules.LoanPreparationBusRules.afterFillForm(LoanPreparationBusRules.java:275)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5455)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4831)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1173)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5402)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4831)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)
	at edu.ku.brc.af.ui.forms.MultiView.showView(MultiView.java:866)
	at edu.ku.brc.af.ui.forms.MultiView.showView(MultiView.java:804)
	at edu.ku.brc.af.ui.forms.MenuSwitcherPanel$SwitcherAL.actionPerformed(MenuSwitcherPanel.java:264)
	at edu.ku.brc.ui.DropDownButtonStateful.doAdvanceToNextState(DropDownButtonStateful.java:261)
	at edu.ku.brc.ui.DropDownButtonStateful.access$000(DropDownButtonStateful.java:59)
	at edu.ku.brc.ui.DropDownButtonStateful$2.actionPerformed(DropDownButtonStateful.java:187)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by maxxxxxdlp** [comment]
After trying to save a CO with the "Save" button being disabled due to the above-mentioned exception, I restarted Specify, and now I am getting this error when trying to create a new CO:

![Screenshot_2021-08-13_19-43-46](https://user-images.githubusercontent.com/40512816/129392332-399b6636-6b30-4302-abd9-c56f59ff67d0.png)

**Comment by tlammer** [comment]
@maxxxxxdlp did you save the loan you created?  I'm not seeing this issue.

**Comment by tlammer** [comment]
If I create a loan pointing to a prep but don't save, then create a gift, pointing to the same prep but using all of the count, save that gift, then try to save the loan, I get the following error in the error log:
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is falsejava.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:147)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:147)	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:147)
	at edu.ku.brc.af.ui.forms.validation.ValSpinner.setRange(ValSpinner.java:128)
	at edu.ku.brc.af.ui.forms.validation.ValSpinner.setRange(ValSpinner.java:128)	at edu.ku.brc.af.ui.forms.validation.ValSpinner.setRange(ValSpinner.java:128)
	at edu.ku.brc.specify.datamodel.busrules.LoanPreparationBusRules.afterFillForm(LoanPreparationBusRules.java:283)
	at edu.ku.brc.specify.datamodel.busrules.LoanPreparationBusRules.afterFillForm(LoanPreparationBusRules.java:283)	at edu.ku.brc.specify.datamodel.busrules.LoanPreparationBusRules.afterFillForm(LoanPreparationBusRules.java:283)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5455)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5455)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5455)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4831)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4831)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4831)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4429)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1214)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1173)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1173)	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1173)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5402)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5402)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5402)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4998)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3121)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3121)	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3121)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:876)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:876)	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:876)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at java.awt.Component.processMouseEvent(Component.java:6539)	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Component.processEvent(Component.java:6304)	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Container.processEvent(Container.java:2239)	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.dispatchEvent(Component.java:4711)	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.dispatchEvent(Component.java:4711)	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue.access$500(EventQueue.java:97)	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:709)	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.awt.EventQueue$3.run(EventQueue.java:703)	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:733)	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:731)	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
