### ISSUE TITLE
Exception when trying to create a Gift for CO without a preparation

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1043]
1. Select "Gift" in the interactions side bar
2. Specify a Catalog Number of a CO that does not have a preparation
3. This exception occurrs:

```yaml
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: The encoded form specification must not be empty, or whitespace. See FormUtils.isBlank(String)
	at com.jgoodies.forms.util.FormUtils.assertNotBlank(FormUtils.java:71)
	at com.jgoodies.forms.layout.FormSpec.parseAndInitValues(FormSpec.java:267)
	at com.jgoodies.forms.layout.FormSpec.<init>(FormSpec.java:181)
	at com.jgoodies.forms.layout.RowSpec.<init>(RowSpec.java:151)
	at com.jgoodies.forms.layout.RowSpec.decodeExpanded(RowSpec.java:230)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:142)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:118)
	at com.jgoodies.forms.layout.RowSpec.decodeSpecs(RowSpec.java:270)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:402)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:359)
	at edu.ku.brc.specify.ui.SelectPrepsDlg.createUI(SelectPrepsDlg.java:168)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.prepsLoaded(InteractionsProcessor.java:452)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.done(InteractionsProcessor.java:774)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The "Enter Collection Object Identifiers" dialog closes and nothing else happens on the screen

**Comment by maxxxxxdlp** [comment]
Same problem with Loans, Disposals and everything else

**Comment by tlammer** [comment]
I cannot reproduce this bug.  @maxxxxxdlp can you do a bit more testing to narrow down the causes for it. corretto version, only on linux, etc.

**Comment by maxxxxxdlp** [comment]
Unable to reproduce this after recreating the database. It might have been caused by https://github.com/specify/specify6/issues/1042 (as it also caused https://github.com/specify/specify6/issues/1042#issuecomment-898586496 and https://github.com/specify/specify6/issues/1042#issuecomment-898591013)
