### ISSUE TITLE
Table 'specify.preparation' doesn't exist, when saving a CO

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1045]
Newly created database. Default forms

See error message in the logs:
![Screenshot (2)](https://user-images.githubusercontent.com/40512816/129582879-3bf74c27-18d4-4fc0-ba5f-94cc03174f08.png)

Windows 10
Latest Specify 6 build
MySQL 5.6
Amazon Corretto 8
![Screenshot (3)](https://user-images.githubusercontent.com/40512816/129582877-63e64711-3b09-4edf-8737-af25b1fce26c.png)

**Comment by maxxxxxdlp** [comment]
When I removed all preparations and tried to save again, I got this exception:
```yaml
09:50:01 ERROR org.hibernate.LazyInitializationException:19 - failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.CollectionObject.preparations, no session or session was closed
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.CollectionObject.preparations, no session or session was closed
        at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
        at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
        at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
        at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
        at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
        at edu.ku.brc.af.ui.forms.FormHelper.updateLastEdittedInfo(FormHelper.java:107)
        at edu.ku.brc.af.ui.forms.FormViewObj.traverseToSetModified(FormViewObj.java:1753)
        at edu.ku.brc.af.ui.forms.FormViewObj.traverseToSetModified(FormViewObj.java:1765)
        at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2819)
        at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3089)
        at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
        at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:876)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by maxxxxxdlp** [comment]
Updating to MariaDB 10.4 as per @tlammer's suggestion fixed the issue
