### ISSUE TITLE
ExchangeOutPrep '+'  button doesn't work.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#1063]
Clicking on the '+' button for exchange out preps pops up a useless dlg.

**Comment by tlammer** [comment]
Get an error when selecting to add an uncataloged item
java.lang.IllegalArgumentException: The encoded form specification must not be empty, or whitespace. See FormUtils.isBlank(String)java.lang.IllegalArgumentException: The encoded form specification must not be empty, or whitespace. See FormUtils.isBlank(String)
	at com.jgoodies.forms.util.FormUtils.assertNotBlank(FormUtils.java:71)
	at com.jgoodies.forms.util.FormUtils.assertNotBlank(FormUtils.java:71)	at com.jgoodies.forms.util.FormUtils.assertNotBlank(FormUtils.java:71)
	at com.jgoodies.forms.layout.FormSpec.parseAndInitValues(FormSpec.java:267)
	at com.jgoodies.forms.layout.FormSpec.parseAndInitValues(FormSpec.java:267)	at com.jgoodies.forms.layout.FormSpec.parseAndInitValues(FormSpec.java:267)
	at com.jgoodies.forms.layout.FormSpec.<init>(FormSpec.java:181)
	at com.jgoodies.forms.layout.FormSpec.<init>(FormSpec.java:181)	at com.jgoodies.forms.layout.FormSpec.<init>(FormSpec.java:181)
	at com.jgoodies.forms.layout.RowSpec.<init>(RowSpec.java:151)
	at com.jgoodies.forms.layout.RowSpec.<init>(RowSpec.java:151)	at com.jgoodies.forms.layout.RowSpec.<init>(RowSpec.java:151)
	at com.jgoodies.forms.layout.RowSpec.decodeExpanded(RowSpec.java:230)
	at com.jgoodies.forms.layout.RowSpec.decodeExpanded(RowSpec.java:230)	at com.jgoodies.forms.layout.RowSpec.decodeExpanded(RowSpec.java:230)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:142)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:142)	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:142)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:118)
	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:118)	at com.jgoodies.forms.layout.FormSpecParser.parseRowSpecs(FormSpecParser.java:118)
	at com.jgoodies.forms.layout.RowSpec.decodeSpecs(RowSpec.java:270)
	at com.jgoodies.forms.layout.RowSpec.decodeSpecs(RowSpec.java:270)	at com.jgoodies.forms.layout.RowSpec.decodeSpecs(RowSpec.java:270)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:402)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:402)	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:402)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:359)
	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:359)	at com.jgoodies.forms.layout.FormLayout.<init>(FormLayout.java:359)
	at edu.ku.brc.specify.ui.SelectPrepsDlg.createUI(SelectPrepsDlg.java:168)
	at edu.ku.brc.specify.ui.SelectPrepsDlg.createUI(SelectPrepsDlg.java:168)	at edu.ku.brc.specify.ui.SelectPrepsDlg.createUI(SelectPrepsDlg.java:168)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.prepsLoaded(InteractionsProcessor.java:452)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.prepsLoaded(InteractionsProcessor.java:452)	at edu.ku.brc.specify.tasks.InteractionsProcessor.prepsLoaded(InteractionsProcessor.java:452)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.done(InteractionsProcessor.java:774)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.done(InteractionsProcessor.java:774)	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.done(InteractionsProcessor.java:774)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue.access$500(EventQueue.java:97)	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:709)	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.awt.EventQueue$3.run(EventQueue.java:703)	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by norinespears** [comment]
I checked this in Exchange Out, Gift, Disposal and Loan.
