### ISSUE TITLE
Opening the Taxon query builder a second time causes a memory heap issue

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#113]
I opened the taxon query builder, then opened the CO query builder, then went back to Taxon and after 6 minutes (6.05.4 according to the stop watch), Specify stayed on the CO query builder and the messages saying it was trying to load the taxon query builder went away.  this message in the error log.
I did this a few times and I think the first time, the same thing happened after a little over 4 minutes.
In the 20180328_17_30 release

Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap spacejava.lang.OutOfMemoryError: Java heap space
	at java.lang.Object.clone(Native Method)
	at java.lang.Object.clone(Native Method)	at java.lang.Object.clone(Native Method)
	at edu.ku.brc.specify.tasks.subpane.qb.BaseQRI.clone(BaseQRI.java:125)
	at edu.ku.brc.specify.tasks.subpane.qb.BaseQRI.clone(BaseQRI.java:125)	at edu.ku.brc.specify.tasks.subpane.qb.BaseQRI.clone(BaseQRI.java:125)
	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.addFieldClone(TableQRI.java:124)
	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.addFieldClone(TableQRI.java:124)	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.addFieldClone(TableQRI.java:124)
	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.clone(TableQRI.java:438)
	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.clone(TableQRI.java:438)	at edu.ku.brc.specify.tasks.subpane.qb.TableQRI.clone(TableQRI.java:438)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.setTableQRIClone(TableTree.java:266)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.setTableQRIClone(TableTree.java:266)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.setTableQRIClone(TableTree.java:266)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:248)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:248)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:248)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:241)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fixAliases(QueryBldrPane.java:5180)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fixAliases(QueryBldrPane.java:5180)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fixAliases(QueryBldrPane.java:5180)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.createNewList(QueryBldrPane.java:3695)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.createNewList(QueryBldrPane.java:3695)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.createNewList(QueryBldrPane.java:3695)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fillNextList(QueryBldrPane.java:4174)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fillNextList(QueryBldrPane.java:4174)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fillNextList(QueryBldrPane.java:4174)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane$3.valueChanged(QueryBldrPane.java:645)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane$3.valueChanged(QueryBldrPane.java:645)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane$3.valueChanged(QueryBldrPane.java:645)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JList.setSelectedIndex(Unknown Source)
	at javax.swing.JList.setSelectedIndex(Unknown Source)	at javax.swing.JList.setSelectedIndex(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.setupUI(QueryBldrPane.java:1133)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.setupUI(QueryBldrPane.java:1133)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.setupUI(QueryBldrPane.java:1133)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:314)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:314)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:314)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:266)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:266)	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.<init>(QueryBldrPane.java:266)

**Comment by timo11** [comment]
This is horrible.
Also happens in 6.6.06.

**Comment by timo11** [comment]
"Fixed" by removing hybridparent1 and hybridparent2 from querybuilder configuration.

**Comment by yvonneekanim** [comment]
I am able to switch between taxon qb and all others with no delay

**Comment by timo11** [comment]
Works now with hybridparents restored. Could, apparently, also enable taxon - parent in querybuilder.xml, which has been disabled since 2009/1/26, 3 months prior to first Sp6 release.
