### ISSUE TITLE
Error message when updating database from 6.6.06 to 6.7

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#116]
Got this message when I updated the cornell birds database from 6.6.06 to 6.7
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Variable 'optimizer_switch' can't be set to the value of 'derived_merge=off'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.update(BasicSQLUtils.java:1082)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.fixDupPrepGuids(SpecifySchemaUpdateService.java:2546)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.manuallyFixDB(SpecifySchemaUpdateService.java:2500)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.updateSchema(SpecifySchemaUpdateService.java:495)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.doLoginContinuing2(DatabaseLoginPanel.java:1387)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17$2.exited(DatabaseLoginPanel.java:1357)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.exited(Unknown Source)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.run(Unknown Source)

**Comment by tlammer** [comment]
5.6

**Comment by timo11** [comment]
5.6 doesn't have a derived_merge optimizer_switch option. Hopefully the fix will eliminate the exception.

**Comment by tlammer** [comment]
was able to update cornell birds without a problem
