### ISSUE TITLE
Null pointer exception when making BE changes

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#117]
I pulled fields into BE via CO query, Assigned a lat, long, max uncert est,& max unvert est unit to one existing locality, removed a county from one record, and changed the locality for another record.  I tried to apply and was warned to close data tabs.  Tried to apply again and got the null pointer exception below.  I'm putting the database along with the query I used and a screen shot of the changes in the databases for programmers directory 

java.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.checkOverrides(UploadTable.java:3338)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.checkOverrides(UploadTable.java:3338)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.checkOverrides(UploadTable.java:3338)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getOverridesForExportedRecMatching(UploadTable.java:3314)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getOverridesForExportedRecMatching(UploadTable.java:3314)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getOverridesForExportedRecMatching(UploadTable.java:3314)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteriaFromExportedRecord(UploadTable.java:3384)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteriaFromExportedRecord(UploadTable.java:3384)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteriaFromExportedRecord(UploadTable.java:3384)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteria(UploadTable.java:3480)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteria(UploadTable.java:3480)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getUpdateMatchCriteria(UploadTable.java:3480)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getMatchCriteria(UploadTable.java:3542)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getMatchCriteria(UploadTable.java:3542)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getMatchCriteria(UploadTable.java:3542)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:4306)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:4306)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:4306)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:5830)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:5830)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.findMatch(UploadTable.java:5830)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5867)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5867)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5867)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5679)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5679)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5679)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5530)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5530)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5530)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5494)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5494)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5494)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4477)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4477)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4477)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)

**Comment by yvonneekanim** [comment]
BE now acknowledges the changes made using georef converter tool but after changes have been applied in the batch editor, the records revert back to the old format in query results and form view.  (see comment in #123 )

**Comment by yvonneekanim** [comment]
Form view shows correct format
