### ISSUE TITLE
BE: Distinct query checkbox error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#129]
If you run a query with distinct and series checked you get a stack trace for an array index out of bounds exception

**Comment by tlammer** [comment]
Couldn't find the ViewDef for formtable definition name[Colljava.lang.ArrayIndexOutOfBoundsException: Array index out of range: 17
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 17java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 17
	at java.util.Vector.get(Unknown Source)
	at java.util.Vector.get(Unknown Source)	at java.util.Vector.get(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.qb.Smusher.smush(Smusher.java:130)
	at edu.ku.brc.specify.tasks.subpane.qb.Smusher.smush(Smusher.java:130)	at edu.ku.brc.specify.tasks.subpane.qb.Smusher.smush(Smusher.java:130)
	at edu.ku.brc.specify.tasks.subpane.qb.QBQueryForIdResultsHQL.cacheFilled(QBQueryForIdResultsHQL.java:395)
	at edu.ku.brc.specify.tasks.subpane.qb.QBQueryForIdResultsHQL.cacheFilled(QBQueryForIdResultsHQL.java:395)	at edu.ku.brc.specify.tasks.subpane.qb.QBQueryForIdResultsHQL.cacheFilled(QBQueryForIdResultsHQL.java:395)
	at edu.ku.brc.specify.tasks.subpane.qb.QBResultSetTableModel.exectionDone(QBResultSetTableModel.java:315)
	at edu.ku.brc.specify.tasks.subpane.qb.QBResultSetTableModel.exectionDone(QBResultSetTableModel.java:315)	at edu.ku.brc.specify.tasks.subpane.qb.QBResultSetTableModel.exectionDone(QBResultSetTableModel.java:315)
	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:369)
	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:369)	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:369)
	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:198)
	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:198)	at edu.ku.brc.dbsupport.JPAQuery.execute(JPAQuery.java:198)
	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:89)
	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:89)	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:89)
	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:85)
	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:85)	at edu.ku.brc.dbsupport.QueryExecutor$1.call(QueryExecutor.java:85)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)

**Comment by timo11** [comment]
Seems to be fixed. I think series and distinct needed to be checked.

**Comment by timo11** [comment]
I actually get the error any time I run any query with series and distinct checked anywhere.

**Comment by timo11** [comment]
Still broken. Series and Distinct can't be checked at the same time.

**Comment by timo11** [comment]
Should be possible to use series and distinct at the same time.
When queries saved with series or distinct checked are opened and run in the batch editor, the checks are ignored, they run as if series and distinct are not checked.

**Comment by garrettgirard** [comment]
I am still getting the following exception:
INSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple Locality Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple Locality Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
ok
INSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple Locality Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple Locality Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
okINSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple Locality Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple Locality Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
ok
INSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple GeoCoord Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple GeoCoord Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
ok
INSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple GeoCoord Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple GeoCoord Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
okINSERT-> INSERT INTO exception ( TimestampCreated,TaskName,Title,Bug,Comments,Id,StackTrace,ClassName,OSName,OSVersion,JavaVersion,JavaVendor,UserName,IP,AppVersion,Collection,Discipline,Division,Institution) VALUES('18-04-11 14:50:24', '', '', '', 'Multiple GeoCoord Detail Records - Count: 0', 'fa341824-173a-0988-6119-3b90cafcd922--162b6f21830', 'Multiple GeoCoord Detail Records - Count: 0', 'edu.ku.brc.specify.config.CheckDBAfterLogin', 'Windows 7', '6.1', '1.8.0_152', 'Oracle Corporation', 'g778g663', '169.254.88.15', '6.7.00', 'Ichthyology', 'Ichthyology', 'Ichthyology', 'Virginia Institute of Marine Science') 
ok
This happens after I run the saved query that has both series and distinct checked. I also noticed that the series and distinct options are no longer available in the batch editor query (if they were previously). So at this point I'm not sure if the fix worked or not. What should be happening?

**Comment by timo11** [comment]
You get those exceptions after you run the query?
Those seem to be messages sent at startup to specify6prod about there being more than one geocoorddetail and localitydetail records for some localities in that db.
Series and Distinct have not been available for be queries for a long time.

**Comment by garrettgirard** [comment]
Actually you are right, those appeared after the startup. So this appears to be working now.

**Comment by timo11** [comment]
The duplicate localitydetail and geocoorddetail records in that db should be fixed. And that db shouldn't be tested with.
