### ISSUE TITLE
Clicking on CO query results generates error

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#197]
In databases in the last release (20181017), when a record from a CO query result is clicked on it generates an error. When the pop up is closed, it appears two more times before a blank CO page is returned. Here's the error message:

java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.ku.brc.specify.ui.PartialDateFormatter.formatToUI(PartialDateFormatter.java:98)
	at edu.ku.brc.af.ui.forms.validation.ValFormattedTextField.setValue(ValFormattedTextField.java:1131)
	at edu.ku.brc.specify.plugins.PartialDateUI.setValue(PartialDateUI.java:435)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUIComp(FormViewObj.java:5705)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5080)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4870)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4715)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4301)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.showView(MultiView.java:864)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:287)
	at edu.ku.brc.af.ui.forms.ViewFactory.createItem(ViewFactory.java:1982)
	at edu.ku.brc.af.ui.forms.ViewFactory.processRows(ViewFactory.java:2181)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2588)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.showView(MultiView.java:815)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:287)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:146)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:426)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:214)
	at edu.ku.brc.specify.tasks.DataEntryTask.createFormFor(DataEntryTask.java:580)
	at edu.ku.brc.specify.tasks.DataEntryTask.editData(DataEntryTask.java:1768)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1832)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2214)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.specify.tasks.subpane.ESResultsTablePanel$ESTableAction$1.run(ESResultsTablePanel.java:1098)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by yvonneekanim** [comment]
Forms containing partial dates can be open with no errors
