### ISSUE TITLE
Add way to calculate number of items on loan on the loan form

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#206]
Request by Queensland - they would like to see the number of items on loan on the loan form.

**Comment by tlammer** [comment]
Also requested by UMich

**Comment by yvonneekanim** [comment]
Is there something I need to add to the form to test this?

**Comment by timo11** [comment]
I guess something should be added to the documentation for this.

Also, I suspect that forms with the new fields won't work in 7. I don't if we need to worry about that now or if we can wait on it and worry later.

**Comment by tlammer** [comment]
are these fields like the quantity field?  I'm wondering if I can just copy that code and change the field names

**Comment by timo11** [comment]
Probably. They should also be readonly.

**Comment by yvonneekanim** [comment]
Works by adding the rows below to loan viewdef:

                <row>
                    <cell type="label" label="Total Items:" initialize="align=right"/>
                    <cell type="field" id="ti" name="totalItems" uitype="spinner" readonly="true"/>
                    <cell type="label" label="Total Quantities:" initialize="align=right"/>
                    <cell type="field" id="tq" name="totalQuantities" uitype="spinner" readonly="true"/>
                    <cell type="label" label="Unresolved Items:" initialize="align=right"/>
                    <cell type="field" id="ui" name="unresolvedItems" uitype="spinner" readonly="true"/>
                    <cell type="label" label="Unresolved Quantities:" initialize="align=right"/>
                    <cell type="field" id="uq" name="unresolvedQuantities" uitype="spinner" readonly="true"/>
                </row>

**Comment by yvonneekanim** [comment]
They counts are all accurate. New loan entries have to be saved and closed before the counts show up on the forms

**Comment by timo11** [comment]
see #724

**Comment by timo11** [comment]
The fields have been renamed as follows:

totalPreps: the number of items in the loan - loan preparations in the loan items sub form..
totalItems: the sum of the quantities of the loan preparations.
unresolvedPreps: the number of loan preparations that are not resolved.
unresolvedItems: the sum of unresolved quantities of loan preparations.

**Comment by yvonneekanim** [comment]
I'm getting error messages when I open the loan form

class_name: edu.ku.brc.af.ui.forms.DataGetterForObj
comments: 

stack_trace: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at edu.ku.brc.af.ui.forms.DataGetterForObj.getFieldValue(DataGetterForObj.java:172)
	at edu.ku.brc.ui.UIHelper.getFieldValues(UIHelper.java:1529)
	at edu.ku.brc.ui.UIHelper.getFieldValues(UIHelper.java:1571)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5262)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4943)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4776)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4374)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:468)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:290)
	at edu.ku.brc.specify.tasks.InteractionsTask.addPrepsToLoan(InteractionsTask.java:1021)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:255)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:161)
	at edu.ku.brc.specify.tasks.InteractionsTask.processInteractionsCommands(InteractionsTask.java:2326)
	at edu.ku.brc.specify.tasks.InteractionsTask.doCommand(InteractionsTask.java:2525)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at edu.ku.brc.specify.datamodel.Loan.getResolvedItems(Loan.java:733)
	... 58 more

task_name: Interactions
title: 
id: f976b698-1604-8199-ff51-b3987e22e306--1717f52ff70
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_202
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 300180088
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00
collection: Ento
discipline: Entomology
division: Ento
institution: m
Collection_number: 1581968728.5359
Discipline_number: 1581968728.1732
Division_number: 1581968727.943
Institution_number: 1581968726.0649
email: t

**Comment by timo11** [comment]
That looks like a problem with an incorrect field name for a calculated field. But it works for me and it looks like I pushed the right form. The calculated fields should be defined like so:
`                <row>
                    <cell type="label" label="Total Preps:" initialize="align=right"/>
                    <cell type="field" id="ti" name="totalPreps" uitype="text" readonly="true"/>
                    <cell type="label" label="Total Items:" initialize="align=right"/>
                    <cell type="field" id="tq" name="totalItems" uitype="text" readonly="true"/>
                </row>
                <row>
                    <cell type="label" label="Resolved Preps:" initialize="align=right"/>
                    <cell type="field" id="ri" name="resolvedPreps" uitype="text" readonly="true"/>
                    <cell type="label" label="Resolved Items:" initialize="align=right"/>
                    <cell type="field" id="rq" name="resolvedItems" uitype="text" readonly="true"/>
                    <cell type="label" label="Unresolved Preps:" initialize="align=right"/>
                    <cell type="field" id="ui" name="unresolvedPreps" uitype="text" readonly="true"/>
                    <cell type="label" label="Unresolved Items:" initialize="align=right"/>
                    <cell type="field" id="uq" name="unresolvedItems" uitype="text" readonly="true"/>
                </row>
`

**Comment by yvonneekanim** [comment]
@norinespears is getting the same issue. Maybe something happened with the form?
