### ISSUE TITLE
WorkBench datasets that include fields which are not defined in trees throw error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#21]
If you try to import or run a dataset that includes any tree fields (such as subspecies) that have not yet been added in the tree definition cause the following error, and will not allow you to use the workbench:

class_name: edu.ku.brc.specify.tasks.WorkbenchTask
comments: 

stack_trace: 
java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.buildValidator(WorkbenchPaneSS.java:4303)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.buildValidator(WorkbenchPaneSS.java:4243)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.<init>(WorkbenchPaneSS.java:418)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.doIt(WorkbenchEditorCreator.java:214)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.access$100(WorkbenchEditorCreator.java:39)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(WorkbenchEditorCreator.java:71)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(WorkbenchEditorCreator.java:67)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

task_name: Workbench
title: 
id: fa341824-173a-0988-6119-3b90cafcd922--160e9b03740
os_name: Windows 7
os_version: 6.1
java_version: 1.8.0_152
java_vendor: Oracle Corporation
max_memory: 954728448
used_memory: 298214368
user_name: g778g663
ip: 169.254.88.15
app_version: 6.6.06
collection: Invertebrate Paleontology
discipline: Invertebrate Paleontology
division: Division
institution: Specify Software Collections
Collection_number: 1515172189.1353
Discipline_number: 1515172188.4338
Division_number: 1515435901.9519
Institution_number: 1515104796.7204
email: demouser@specify.org

**Comment by garrettgirard** [comment]
You will get the same error when working with datasets that have missing required fields (i.e. if you have Accession fields, but not Accession number).
