### ISSUE TITLE
Can't upload dataset with certain fields

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#22]
Whenever I try to upload a recordset with the CO Citation field, I get the following exception and WorkBench stops the upload:

edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.title
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.titleedu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.title
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6097)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6097)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6097)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5780)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5780)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5780)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5619)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5619)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5619)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5463)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5463)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5463)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5427)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5427)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5427)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4430)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4430)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4430)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.title
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.titleCaused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ReferenceWork.title
	at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)
	at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)	at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:495)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:495)	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:495)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.saveOrUpdate(HibernateDataProviderSession.java:549)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.saveOrUpdate(HibernateDataProviderSession.java:549)	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.saveOrUpdate(HibernateDataProviderSession.java:549)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6066)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6066)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6066)
	... 11 more
	... 11 more	... 11 more

**Comment by garrettgirard** [comment]
I got a similar exception for Geography.Name.

**Comment by garrettgirard** [comment]
Same with PrepType.name.

**Comment by garrettgirard** [comment]
Same with Taxon.name (I'm pretty sure any taxon rank will cause this one).

**Comment by garrettgirard** [comment]
Yvonne has not been getting these exceptions and they may be specific to the demodatabase found in Z:\Specify6\Databases\Demo Databases called DemoNeedsFishlinked.sql

**Comment by tlammer** [comment]
​Try that in the regular 6.6.06.  I think I was having similar issues when working on uploading data in the external

________________________________

**Comment by garrettgirard** [comment]
I am not getting these exceptions when I test the same database and recordset in 6.6.06 external. This kind of thing may happen in other databases/collections as well. I have been testing in the demodatabase invertpaleo collection.

**Comment by tlammer** [comment]
and lithostrat name but not chronostrat

**Comment by timo11** [comment]
citations and preptypes are working for me now. Didn't check others.
