### ISSUE TITLE
Using a WB dataset with WB config files different from those it was created with can lead to multiple problems.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#236]
If you create a Dataset with custom WB config files, then use the WB while running an instance of Specify that is using WB config files that do not include mappings the dataset uses, many bad things can happen. Such as, for example...

Uploads will succeed, but the 'de-mapped' columns will not be uploaded. 
When editing the dataset template the de-mapped columns will not be displayed.
If columns are added or shifted in the template, exisiting columns' values may be lost, or transferred to other columns.
Exports and imports get weird too.

see #234 and #233.

**Comment by timo11** [comment]
When opening a dataset for editing, or to edit its mappings, if specify is unable to find an schema item for a field, it prints a message that the dataset cannot be loaded because of an unknown field with the field's table, name, caption, and original column header.

**Comment by yvonneekanim** [comment]
I'm getting this error whenever I try to do a workbench mapping. 

java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.TemplateEditor.createUI(TemplateEditor.java:247)
	at edu.ku.brc.specify.tasks.subpane.wb.TemplateEditor.<init>(TemplateEditor.java:187)
	at edu.ku.brc.specify.tasks.WorkbenchTask.showColumnMapperDlg(WorkbenchTask.java:723)
	at edu.ku.brc.specify.tasks.WorkbenchTask.createNewWorkbench(WorkbenchTask.java:1663)
	at edu.ku.brc.specify.tasks.WorkbenchTask.createNewWorkbenchFromFile(WorkbenchTask.java:1621)
	at edu.ku.brc.specify.tasks.WorkbenchTask.processWorkbenchCommands(WorkbenchTask.java:4374)
	at edu.ku.brc.specify.tasks.WorkbenchTask.doCommand(WorkbenchTask.java:4477)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by timo11** [comment]
Should work in v6.7.02_internal_i

**Comment by yvonneekanim** [comment]
Datasets cannot be opened/edited when there is a field missing from the wb datamodel. There is a warning message that lets users know the field is not in the workbench schema.
