### ISSUE TITLE
Exception when using Preparation Properties and scrolling between collection objects

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#243]
Steps:
1) add prep properties to preps
2) check Save and New in Data menu
3) Configure carry forward
4) start adding data to the form add multiple preps with multiple pp's
5) click save and new
6) go back to original record, make any edit to activate Save/New button again
7) click Save/New

Data does not seem to carry forward and the error log will have a similar exception to below

Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.Preparation.preparationProperties, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
	at java.util.Collections$3.<init>(Unknown Source)
	at java.util.Collections.enumeration(Unknown Source)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4593)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4301)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5274)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4870)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4703)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4301)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5274)
	at edu.ku.brc.af.ui.forms.FormViewObj.indexChanged(FormViewObj.java:6592)
	at edu.ku.brc.af.ui.forms.ResultSetController.notifyListeners(ResultSetController.java:798)
	at edu.ku.brc.af.ui.forms.ResultSetController$13.run(ResultSetController.java:550)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by yvonneekanim** [comment]
Preparations and properties are carried forward when save/new is used.
