### ISSUE TITLE
Null pointer when deleting collections

### ISSUE THREAD

**Issue by timo11** [specify/specify6#250]

**Comment by timo11** [comment]
exception when SI delete collections with data in them. Newly created collections





class_name: edu.ku.brc.af.tasks.StatsTrackerTask

comments: 


stack_trace: 

java.lang.NullPointerException

	at edu.ku.brc.specify.tasks.StatsTrackerTask.appendBasicCollStatsStat(StatsTrackerTask.java:337)

	at edu.ku.brc.specify.tasks.StatsTrackerTask.appendBasicCollStats(StatsTrackerTask.java:385)

	at edu.ku.brc.specify.tasks.StatsTrackerTask.collectSecondaryStats(StatsTrackerTask.java:282)

	at edu.ku.brc.af.tasks.StatsTrackerTask.createPostParameters(StatsTrackerTask.java:534)

	at edu.ku.brc.af.tasks.StatsTrackerTask.sendStats(StatsTrackerTask.java:300)

	at edu.ku.brc.specify.tasks.StatsTrackerTask.sendStats(StatsTrackerTask.java:262)

	at edu.ku.brc.af.tasks.StatsTrackerTask$1.doInBackground(StatsTrackerTask.java:171)

	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at javax.swing.SwingWorker.run(SwingWorker.java:334)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)


task_name: 

title: 

id: aaad4543-5fc9-a988-c8c7-0e11e8e786f5--16926d67a00

os_name: Mac OS X

os_version: 10.12.6

java_version: 1.8.0_192

java_vendor: Oracle Corporation

max_memory: 954728448

used_memory: 113648592

user_name: specify

ip: 169.254.24.238

app_version: 6.7.02

collection: m

discipline: Botany

division: m

institution: m

Collection_number: 1531845770.976

Discipline_number: 1531845770.5167

Division_number: 1531845770.2983

Institution_number: 1531845766.5183

email: m

**Comment by tlammer** [comment]
still getting this as well.

**Comment by tlammer** [comment]
ignore previous comment.  I read it as collection object not collection

**Comment by yvonneekanim** [comment]
I'm no longer getting the exceptions
