### ISSUE TITLE
two users can open one dataset at the same time

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#257]
I transferred a data set to another user.  it disappeared from my workbench sidebar but stayed on the welcome screen and I could open it.  I then opened the same dataset as the other user (from the workbench sidebar)

**Comment by tlammer** [comment]
no exceptions in the logs

**Comment by tlammer** [comment]
exception that occurs if you try to save changes to a record set you no longer own: edu.ku.brc.dbsupport.StaleObjectException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.Workbench#2]
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.commit(HibernateDataProviderSession.java:635)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.saveObject(WorkbenchPaneSS.java:3748)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$5$1.construct(WorkbenchPaneSS.java:473)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.Workbench#2]
	at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:1765)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2407)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2307)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2607)
	at org.hibernate.action.EntityUpdateAction.execute(EntityUpdateAction.java:92)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:234)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.commit(HibernateDataProviderSession.java:630)
	... 4 more

**Comment by timo11** [comment]
same as #255

**Comment by tlammer** [comment]
fix for #255 fixed this
