### ISSUE TITLE
Workbench Validation Issue

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#26]
I'm not sure what caused it, but my workbench upload failed in the build batchyfog. This is the exception found in the logs:

edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: FinishDepth does not support seq > 0
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: FinishDepth does not support seq > 0edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: FinishDepth does not support seq > 0
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTableTree.finishDepth(UploadTableTree.java:1100)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTableTree.finishDepth(UploadTableTree.java:1100)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTableTree.finishDepth(UploadTableTree.java:1100)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5762)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5762)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:5762)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5579)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5579)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5579)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5522)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5522)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5522)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5486)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5486)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5486)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4486)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4486)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$13.doInBackground(Uploader.java:4486)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)

**Comment by garrettgirard** [comment]
This is WorkBench, not BE. I was uploading a test dataset and it gave me this exception. It can be found following this path: Z:\Specify6\Tester Documentation\Specify 7 Testing Data\Spreadsheets
It's called Collection Object(3)
