### ISSUE TITLE
BE: Error in batch editing when Locality Details in CO query

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#27]
I created a CO query in the ento collection of the demo database and included a field from locality details.  I switched to batch editing and double clicked a field to edit it (not a locality details field) and this error popped up.

failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.Locality.localityDetails, no session or session was closed

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.Locality.localityDetails, no session or session was closed
    at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
    at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
    at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
    at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
    at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.getChildRecords(UploadTable.java:1463)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.loadRecord(UploadTable.java:1412)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.loadRecord(UploadTable.java:1393)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.loadRecord(UploadTable.java:1393)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.loadExportedRecord(UploadTable.java:1357)
    at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.checkChangedData(Uploader.java:1744)
    at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchValidator.endCellEdit(WorkbenchValidator.java:96)
    at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.updateRowValidationStatus(WorkbenchPaneSS.java:4873)
    at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$GridCellEditor.stopCellEditing(WorkbenchPaneSS.java:5586)
    at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at edu.ku.brc.ui.tmanfe.SpreadSheet.processMouseEvent(SpreadSheet.java:819)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tlammer** [comment]
I still get the error in the heap release

**Comment by timo11** [comment]
what query? what records? what field?

**Comment by tlammer** [comment]
I just put a backup of the database in \\rfs.home.ku.edu\groups\BI\Specify\Specify6\Databases\Databases for Programmers
