### ISSUE TITLE
cannot delete data sets if fields are missing from workbench schema

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#292]
I tried to delete an old data set but couldn't because there were fields in the mapping that were no longer in the wb schema configuration files.  I had to add the fields to the xml configuration fields in order to delete the data sets.

**Comment by tlammer** [comment]
it deleted the data set after all, but it threw an unhandled exception before doing so.
edu.ku.brc.specify.tasks.subpane.wb.WBUnMappedItemException: The Dataset cannot be loaded because it contains fields that are not in the current Workbench Schema.
The current Workbench Schema does not contain: agent.postalCode2 (caption: Postal Code 2, column header: Postal Code 2)
	at edu.ku.brc.specify.tasks.WorkbenchTask.getDataType(WorkbenchTask.java:4407)
	at edu.ku.brc.specify.tasks.subpane.wb.XLSExport.getColType(XLSExport.java:133)
	at edu.ku.brc.specify.tasks.subpane.wb.XLSExport.bldColTypes(XLSExport.java:123)
	at edu.ku.brc.specify.tasks.subpane.wb.XLSExport.writeData(XLSExport.java:275)
	at edu.ku.brc.specify.rstools.ExportToFile.processDataList(ExportToFile.java:96)
	at edu.ku.brc.specify.tasks.PluginsTask.doProcessTool(PluginsTask.java:455)
	at edu.ku.brc.specify.tasks.PluginsTask.processToolDataFromList(PluginsTask.java:417)
	at edu.ku.brc.specify.tasks.PluginsTask.processToolList(PluginsTask.java:617)
	at edu.ku.brc.specify.tasks.PluginsTask.doCommand(PluginsTask.java:693)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.specify.tasks.WorkbenchTask.sendExportCommand(WorkbenchTask.java:1547)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchBackupMgr.backupWorkbench(WorkbenchBackupMgr.java:202)
	at edu.ku.brc.specify.tasks.WorkbenchTask$3.construct(WorkbenchTask.java:2249)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at java.lang.Thread.run(Unknown Source)

**Comment by yvonneekanim** [comment]
Which of the workbench files should I be editing to test this? wbschema_localizaton.xml?

**Comment by timo11** [comment]
specify_workbench_datamodel.xml. If you pick a dataset to test, delete a field its mapping contains from specify_workbench_datamodel.xml, then delete the database there should be no exception, and there should be a message in the status bar saying that the dataset was not backed up before deleting, which message may or may not remain displayed long enough to actually be read.

**Comment by yvonneekanim** [comment]
I was able to delete the dataset without errors
