### ISSUE TITLE
Change relationship to allow multiple Extractors and PCR Persons in DNA Sequence

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#315]
SDSMT is trying to add DNA sequences to document their data and noted they often have multiple extractors and multiple PCR persons.

**Comment by timo11** [comment]
What is a PCR person? DNAsequence.sequencer or DNAsequencingrun.extractor?

**Comment by timo11** [comment]
Extractor and Sequencer tables were added, linking Agent and DNASequence. The original Extractor and Sequencer relationships remain.

Remember to force a schema update to existing dbs by backing up spversion.schemaversion, or using the always update pref, whatever it is.

**Comment by tlammer** [comment]
PCR person is not a sequencer.  Can we rename the sequencer table to be PCR person?

**Comment by timo11** [comment]
sequencers are now pcrpeople. Who are probably dnasequecingrun runners or preparers but whatever.

**Comment by maxxxxxdlp** [comment]
I get this error when opening the `DNA Sequence` table:
```
class_name: edu.ku.brc.af.ui.forms.persist.View
comments: 

stack_trace: 
java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.PcrPersonBusRules
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)
	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:350)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2574)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)
	at edu.ku.brc.af.ui.forms.ViewFactory.createItem(ViewFactory.java:1982)
	at edu.ku.brc.af.ui.forms.ViewFactory.processRows(ViewFactory.java:2181)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2588)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:280)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:146)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:426)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:290)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1826)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2214)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.core.NavBoxAction.actionPerformed(NavBoxAction.java:179)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Data_Entry
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--170a6fe98a0
os_name: Mac OS X
os_version: 10.15.4
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2862852792
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1583359855.394
Discipline_number: 1583359854.9909
Division_number: 1583359854.7517
Institution_number: 1583359852.4898
email: 1

```

**Comment by maxxxxxdlp** [comment]
It seems to work. It would be wise if somebody else also tested this. @yvonneekanim can you test this?

**Comment by yvonneekanim** [comment]
It doesn't work for me. See #675
