### ISSUE TITLE
Null Pointer exception running certain reports.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#325]
Reported by emoryherbarium for 'Barcode Label' report.

**Comment by timo11** [comment]
Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:71)
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:71)
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:71)
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:58)
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:58)
at edu.ku.brc.specify.tasks.subpane.qb.QueryParameterPanel.setQuery(QueryParameterPanel.java:58)
at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.runReport(QueryBldrPane.java:2752)
at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.runReport(QueryBldrPane.java:2752)
at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.runReport(QueryBldrPane.java:2752)
at edu.ku.brc.specify.tasks.ReportsBaseTask.runReport(ReportsBaseTask.java:1574)
at edu.ku.brc.specify.tasks.ReportsBaseTask.runReport(ReportsBaseTask.java:1574)
at edu.ku.brc.specify.tasks.ReportsBaseTask.runReport(ReportsBaseTask.java:1574)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:952)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:952)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:952)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.specify.tasks.ReportsBaseTask.printReport(ReportsBaseTask.java:786)
at edu.ku.brc.specify.tasks.ReportsBaseTask.printReport(ReportsBaseTask.java:786)
at edu.ku.brc.specify.tasks.ReportsBaseTask.printReport(ReportsBaseTask.java:786)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:931)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:931)
at edu.ku.brc.specify.tasks.ReportsBaseTask.processReportCommands(ReportsBaseTask.java:931)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsBaseTask.doCommand(ReportsBaseTask.java:1627)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.specify.tasks.ReportsTask.doCommand(ReportsTask.java:83)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.Component.processMouseEvent(Component.java:6539)
at java.awt.Component.processMouseEvent(Component.java:6539)
at java.awt.Component.processMouseEvent(Component.java:6539)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6304)
at java.awt.Component.processEvent(Component.java:6304)
at java.awt.Component.processEvent(Component.java:6304)
at java.awt.Container.processEvent(Container.java:2239)
at java.awt.Container.processEvent(Container.java:2239)
at java.awt.Container.processEvent(Container.java:2239)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Container.dispatchEventImpl(Container.java:2297)
at java.awt.Container.dispatchEventImpl(Container.java:2297)
at java.awt.Container.dispatchEventImpl(Container.java:2297)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
at java.awt.Container.dispatchEventImpl(Container.java:2283)
at java.awt.Container.dispatchEventImpl(Container.java:2283)
at java.awt.Container.dispatchEventImpl(Container.java:2283)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
at java.awt.EventQueue$4.run(EventQueue.java:733)
at java.awt.EventQueue$4.run(EventQueue.java:733)
at java.awt.EventQueue$4.run(EventQueue.java:733)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

​

**Comment by timo11** [comment]
Workaround is to run 'update spqueryfield set isprompt = false where isprompt is null;'

**Comment by yvonneekanim** [comment]
Tested in Emory database using barcode label. Report runs without any errors
