### ISSUE TITLE
BE: If Series is turned on, can't go to batch editing

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#36]
if you turn on Series when query results come in and try to switch to batch edit mode, it returns you to the query page with no explanation and this in the error log:
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 7java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 7
	at java.util.Vector.get(Unknown Source)
	at java.util.Vector.get(Unknown Source)	at java.util.Vector.get(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchTask.loadRsIntoWb(WorkbenchTask.java:1858)
	at edu.ku.brc.specify.tasks.WorkbenchTask.loadRsIntoWb(WorkbenchTask.java:1858)	at edu.ku.brc.specify.tasks.WorkbenchTask.loadRsIntoWb(WorkbenchTask.java:1858)
	at edu.ku.brc.specify.tasks.WorkbenchTask$1.construct(WorkbenchTask.java:2031)
	at edu.ku.brc.specify.tasks.WorkbenchTask$1.construct(WorkbenchTask.java:2031)	at edu.ku.brc.specify.tasks.WorkbenchTask$1.construct(WorkbenchTask.java:2031)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)

**Comment by timo11** [comment]
Series and Distinct checkboxes are not available on BatchEdit QB.
BatchEdit service not available for query results generated with Series or Distinct checked.

**Comment by tlammer** [comment]
they won't be available or they aren't available?  Series is available for me in batch editing query in the glob release
