### ISSUE TITLE
Info Button on interaction prep dialog doesn't always work

### ISSUE THREAD

**Issue by timo11** [specify/specify6#372]
Reported by Andy:

Trying to create a gift and after selecting my items I notice that 5 specimens are unavailable from the first lot:

 

 

However, when I click on the “i” which should bring up the loan/gift in question I get an error and the following stack trace:

 

org.hibernate.hql.ast.QuerySyntaxException: unexpected end of subtree [FROM edu.ku.brc.specify.datamodel.Loan WHERE loanId in()]

                at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:31)

                at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:24)

                at org.hibernate.hql.ast.ErrorCounter.throwQueryException(ErrorCounter.java:59)

                at org.hibernate.hql.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:235)

                at org.hibernate.hql.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:160)

                at org.hibernate.hql.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:111)

                at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:77)

                at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:56)

                at org.hibernate.engine.query.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:72)

                at org.hibernate.impl.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:133)

                at org.hibernate.impl.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:112)

                at org.hibernate.impl.SessionImpl.createQuery(SessionImpl.java:1623)

                at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.getDataList(HibernateDataProviderSession.java:240)

                at edu.ku.brc.specify.ui.SelectPrepsDlg$LoanLoader.doInBackground(SelectPrepsDlg.java:687)

                at edu.ku.brc.specify.ui.SelectPrepsDlg$LoanLoader.doInBackground(SelectPrepsDlg.java:643)

                at javax.swing.SwingWorker$1.call(Unknown Source)

                at java.util.concurrent.FutureTask.run(Unknown Source)

                at javax.swing.SwingWorker.run(Unknown Source)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.lang.Thread.run(Unknown Source)

 

Andy

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute

Dyche Hall
1345 Jayhawk Boulevard
Lawrence, KS, 66045-7561
USA

**Comment by timo11** [comment]
The problem would only occur if the none of the unavailable preps were associated with loans. After the exception a blank loan form would appear.
After the fix, the info button behaves like the 'Show Interactions' button on the preparation form.
When testing the fix, 'show interactions' on the prep form should also be tested.

**Comment by yvonneekanim** [comment]
Show info button displays a subform displaying the interactions. If preparations of a catalog number belong to multiple interactions, subforms display for each interaction.
