### ISSUE TITLE
Agent Search Error

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#375]
Error when searching for an Agent, regardless of search parameters.

Error Code:
class_name: edu.ku.brc.dbsupport.SQLExecutionProcessor
comments:

stack_trace:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'specify_6_8_00.addresses.Address' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
at com.mysql.jdbc.Util.getInstance(Util.java:372)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
at edu.ku.brc.dbsupport.SQLExecutionProcessor.execute(SQLExecutionProcessor.java:253)
at edu.ku.brc.dbsupport.QueryExecutor$2.call(QueryExecutor.java:109)
at edu.ku.brc.dbsupport.QueryExecutor$2.call(QueryExecutor.java:105)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)

![Screenshot from 2019-11-04 09-40-25](https://user-images.githubusercontent.com/40512816/68342981-690ea400-00b1-11ea-912a-8d43cec26a03.png)

**Comment by maxxxxxdlp** [comment]
Tested on Ubuntu 18.04.3 LTS

**Comment by maxxxxxdlp** [comment]
Same error on **macOS 10.15**


<img width="1075" alt="Screen Shot 2019-11-15 at 4 55 27 PM" src="https://user-images.githubusercontent.com/40512816/68981377-c220bb00-07c8-11ea-8b8a-0db5f365069a.png">
<img width="889" alt="Screen Shot 2019-11-15 at 4 55 32 PM" src="https://user-images.githubusercontent.com/40512816/68981378-c220bb00-07c8-11ea-9cfb-b69017e1b9e3.png">



com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'specify.addresses.Address' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at edu.ku.brc.dbsupport.SQLExecutionProcessor.execute(SQLExecutionProcessor.java:253)
	at edu.ku.brc.dbsupport.QueryExecutor$2.call(QueryExecutor.java:109)
	at edu.ku.brc.dbsupport.QueryExecutor$2.call(QueryExecutor.java:105)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by timo11** [comment]
I think this is happening because the sql_mode setting for the server contains ONLY_FULL_GROUP_BY. The server needs to be reconfigured so the sql_mode does not contain the ONLY_FULL_GROUP_BY option.

**Comment by maxxxxxdlp** [comment]
Removed ONLY_FULL_GROUP_BY paramether through phpMyAdmin and everything works fine now.
This setting was enabled by default on both of my mysql servers (on macOS and Linux).
I guess there should be documentation about this issue on Specify webiste, or Specify 6 should show more user-friendly errors.

**Comment by timo11** [comment]
Hopefully the Specify Knowledge Base repo has an entry for this?

**Comment by maxxxxxdlp** [comment]
Seems not to happen when using MariaDB 10.3 instead of MySQL 5.7

**Comment by maxxxxxdlp** [comment]
This error still happens for databases with MySQL 5.7 in the latest version of Specify 6.8

I should note that search for agents works perfectly fine in autocompletes
![Screenshot from 2020-02-25 10-52-51](https://user-images.githubusercontent.com/40512816/75268450-20dcd400-57bd-11ea-8bf4-77f015f4690c.png)

Also, quick search does not throw exceptions
![Screenshot from 2020-02-25 10-52-29](https://user-images.githubusercontent.com/40512816/75268449-20443d80-57bd-11ea-941c-78756bfaf9e0.png)

And most importantly, the agent search works perfectly fine when adding new user in the `Security Tools` window
![Screenshot from 2020-02-25 10-49-45](https://user-images.githubusercontent.com/40512816/75268441-1f131080-57bd-11ea-97f8-937f9a12cada.png)
