### ISSUE TITLE
Java Cast Exception while using Data Exporter

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#389]
After builidng a mapping of Botany Database in Data exporter and clicking export buttons, Java exception is being fired.

Error after clicking on **Export**:
ClassCastException: java.lang.integer cannot be cast to java.lang.Long
The cache could not be exported

Stack Trace after clicking on **Expot for Web Portal**:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at edu.ku.brc.specify.tools.webportal.BuildSearchIndex2.exportWebPortal(BuildSearchIndex2.java:741)
	at edu.ku.brc.specify.tools.webportal.BuildSearchIndex2.index(BuildSearchIndex2.java:891)
	at edu.ku.brc.specify.tools.export.ExportPanel$4$1.doInBackground(ExportPanel.java:398)
	at edu.ku.brc.specify.tools.export.ExportPanel$4$1.doInBackground(ExportPanel.java:390)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Web protal export failed
The cache could not be exported

![Screenshot from 2019-11-08 14-17-59](https://user-images.githubusercontent.com/40512816/68507942-b403f500-0232-11ea-9521-5ed6c323e76e.png)
![Screenshot from 2019-11-08 14-18-03](https://user-images.githubusercontent.com/40512816/68507943-b403f500-0232-11ea-9e7e-a8952d5da82a.png)
![Screenshot from 2019-11-08 14-18-05](https://user-images.githubusercontent.com/40512816/68507944-b403f500-0232-11ea-83e2-096d81c99c78.png)
![Screenshot from 2019-11-08 14-18-13](https://user-images.githubusercontent.com/40512816/68507945-b403f500-0232-11ea-82d9-6e68fb7ff229.png)

**Comment by maxxxxxdlp** [comment]
Specify version: 6.7.0.1

**Comment by maxxxxxdlp** [comment]
Same problem with Specify 6.8.00
Tested using:
**Specify6/Databases/Convertsion Databases/Costa Rica/specify 20180627 0847.sql** database on 6.7.01
**Specify6/Databases/Convertsion Databases/2019_10_28_12_58_00.sql** database on 6.8.00
