### ISSUE TITLE
Add support for .XLSX files

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#398]
It would be more convinient for users if there was an option to import data into workbench from **.xlsx** file. Currently supported **.xls** file is quite old.

**Comment by maxxxxxdlp** [comment]
Also, adding ability to export Data Set and Record Set to `.xlsx` would be appreciated

**Comment by timo11** [comment]
Exporting from query results also uses xlsx format now.
In export dialogs the default file type is xlsx, but you can type in .xls to export as xls if you want to. I think.
Be sure to test: Importing xls files with mappings, iReports, and the import file splitter on xlsx files.

**Comment by maxxxxxdlp** [comment]
Exception when uploading `.xls` file into workbench
[a.xls.zip](https://github.com/specify/specify6/files/5073340/a.xls.zip)



```
class_name: edu.ku.brc.specify.tasks.subpane.wb.ConfigureXLS
comments: 

stack_trace: 
java.io.IOException: Bad file descriptor
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at org.apache.poi.util.IOUtils.readFully(IOUtils.java:279)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:282)
	at edu.ku.brc.specify.tasks.subpane.wb.ConfigureXLS.nonInteractiveConfig(ConfigureXLS.java:518)
	at edu.ku.brc.specify.tasks.subpane.wb.ConfigureXLS.interactiveConfig(ConfigureXLS.java:157)
	at edu.ku.brc.specify.tasks.subpane.wb.ConfigureExternalDataBase.readConfig(ConfigureExternalDataBase.java:202)
	at edu.ku.brc.specify.tasks.subpane.wb.ConfigureXLS.<init>(ConfigureXLS.java:69)
	at edu.ku.brc.specify.tasks.subpane.wb.ImportDataFileInfo.load(ImportDataFileInfo.java:77)
	at edu.ku.brc.specify.tasks.WorkbenchTask.createNewWorkbenchFromFile(WorkbenchTask.java:1585)
	at edu.ku.brc.specify.tasks.WorkbenchTask.processWorkbenchCommands(WorkbenchTask.java:4365)
	at edu.ku.brc.specify.tasks.WorkbenchTask.doCommand(WorkbenchTask.java:4468)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Workbench
title: 
id: fd12a50a-abdd-0bae-2851-ff609cc74a08--173e9d6a890
os_name: Mac OS X
os_version: 10.15.6
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3252749376
user_name: mambo
ip: 192.168.1.11
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1597392208.3512
Discipline_number: 1597392207.8218
Division_number: 1597392207.3036
Institution_number: 1597392205.6381
email: 1

```

**Comment by maxxxxxdlp** [comment]
Works fine with `.xlsx`

**Comment by maxxxxxdlp** [comment]
Data set export to `.xls` and `.xlsx` works fine
@timo11 are the any other places where I should test `.xls` and `.xlsx`?

**Comment by timo11** [comment]
@maxxxxxdlp  test exporting query results. Only xlsx is in the extension filter for the file chooser, but test what happens if you type in an .xls extension. I think it successfully exports to xls.

**Comment by maxxxxxdlp** [comment]
`.xlsx` works fine.
Though, I can't export to `.xls` cause it adds `.xlsx` to the filename regardless of the `File Format` I chose

<img width="265" alt="Screen Shot 2020-08-14 at 8 53 54 PM" src="https://user-images.githubusercontent.com/40512816/90278579-44c9ca00-de70-11ea-93be-96b0d14f4908.png">
<img width="662" alt="Screen Shot 2020-08-14 at 8 53 39 PM" src="https://user-images.githubusercontent.com/40512816/90278594-498e7e00-de70-11ea-83c2-a4d1280f73be.png">

**Comment by timo11** [comment]
bad file descriptor exception (as with a.xls) should be fixed as of 16631c4

**Comment by maxxxxxdlp** [comment]
Exception is fixed
`.xls` export works in Workbench but does not work in query builder (it adds `.xlsx` to a filename anyways)

**Comment by maxxxxxdlp** [comment]
Testing results for XLS and XLSX support in Specify 6:
Importing Taxa from XLSX via SpWizard: **Does not work** (file downloaded from the server, but data not imported)
Importing Taxa from XLS via SpWizard: Works fine
Exporting Query results to XLSX: Works fine
Exporting Query results to XLS: **Does not work** (there is no option for .xls file in the picklist. Specifying a file name with .xls extension with lead to .xlsx be appended to the end of the file name)
Importing data into Workbench from XLSX: Works fine
Importing data into Workbench from XLS: Works fine
Exporting Data Set to XLSX: Works fine
Exporting Data Set to XLS: Works fine

**Comment by timo11** [comment]
x-special/nautilus-clipboard
copy
file:///home/timo/Downloads/image.png

**Comment by timo11** [comment]
![image](https://user-images.githubusercontent.com/2915306/129401573-dafb1526-512b-455c-b53a-be46cafde3ce.png)
![image (1)](https://user-images.githubusercontent.com/2915306/129401609-73d1ee6c-1b05-41d2-808b-d7829b015316.png)

**Comment by timo11** [comment]
Loading saved mappings is not working. first image in comment above is 6.8.00 result, 2nd is for 6.8.01.

Using the file Y:\Specify6\Databases\Demo Databases\DemoData Files\WB Imported Datasets  I used the WBpaleodata.xls

**Comment by maxxxxxdlp** [comment]
Loading saved mappings is working now.
Also, XLS and XLSX test results from https://github.com/specify/specify6/issues/398#issuecomment-706400825 still hold true.
For XLSX support in SpWizard, see https://github.com/specify/specify6/issues/805.
