### ISSUE TITLE
Java Cast Exception

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#399]
Unrecoverable error while trying to backup database in **SpBackupRestore**

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at java.util.Properties.store0(Properties.java:834)
	at java.util.Properties.store(Properties.java:818)
	at edu.ku.brc.af.core.db.BackupServiceFactory.writeStats(Unknown Source)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(Unknown Source)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPool

Executor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

ERROR brc.ui.UIRegistry:? - The was an unrecoverable error during the backup process.
You should try again.

Specify version: **6.7.0.1**
Database: Costa Rica

![Screenshot from 2019-11-15 11-32-00](https://user-images.githubusercontent.com/40512816/68963082-bd91dd80-079b-11ea-9e7d-ef26ed335b09.png)
![Screenshot from 2019-11-15 11-33-12](https://user-images.githubusercontent.com/40512816/68963083-bd91dd80-079b-11ea-9d50-75107252154a.png)
![Screenshot from 2019-11-15 11-33-14](https://user-images.githubusercontent.com/40512816/68963084-bd91dd80-079b-11ea-8c1a-c2a098fcf623.png)
![Screenshot from 2019-11-15 11-33-44](https://user-images.githubusercontent.com/40512816/68963107-cd112680-079b-11ea-9017-9b631b9a8f9c.png)

**Comment by maxxxxxdlp** [comment]
Tested in 6.7.0.4
Same error

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'notifications_message.bk' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.getCount(BasicSQLUtils.java:518)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.getCount(BasicSQLUtils.java:483)
	at edu.ku.brc.af.core.db.BackupServiceFactory.getCollectionStats(BackupServiceFactory.java:230)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:303)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:280)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at java.util.Properties.store0(Properties.java:834)
	at java.util.Properties.store(Properties.java:818)
	at edu.ku.brc.af.core.db.BackupServiceFactory.writeStats(BackupServiceFactory.java:276)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:303)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:280)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
13:37:53 ERROR brc.ui.UIRegistry:1187 - The was an unrecoverable error during the backup process.
You should try again.
13:38:58 ERROR brc.ui.UIRegistry:1187 - java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String


![Screenshot from 2019-11-15 13-38-57](https://user-images.githubusercontent.com/40512816/68970688-76ace380-07ad-11ea-8a57-3a0320d91426.png)
![Screenshot from 2019-11-15 13-38-59](https://user-images.githubusercontent.com/40512816/68970689-76ace380-07ad-11ea-850c-fc1efdc27420.png)
![Screenshot from 2019-11-15 13-40-14](https://user-images.githubusercontent.com/40512816/68970690-76ace380-07ad-11ea-82a9-4bcffbf3c3c2.png)

**Comment by maxxxxxdlp** [comment]
Same error in Specify 6.8

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'notifications_message.bk' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.getCount(BasicSQLUtils.java:532)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.getCount(BasicSQLUtils.java:518)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.getCount(BasicSQLUtils.java:483)
	at edu.ku.brc.af.core.db.BackupServiceFactory.getCollectionStats(BackupServiceFactory.java:230)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:303)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:280)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at java.util.Properties.store0(Properties.java:834)
	at java.util.Properties.store(Properties.java:818)
	at edu.ku.brc.af.core.db.BackupServiceFactory.writeStats(BackupServiceFactory.java:276)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:303)
	at edu.ku.brc.af.core.db.MySQLBackupService$1.doInBackground(MySQLBackupService.java:280)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:11:38 ERROR brc.ui.UIRegistry:1187 - The was an unrecoverable error during the backup process.
You should try again.
12:12:14 ERROR brc.ui.UIRegistry:1187 - java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String



![Screenshot from 2019-11-18 12-12-13](https://user-images.githubusercontent.com/40512816/69078195-f41a6300-09fc-11ea-8e2e-cdfaef1fa095.png)
![Screenshot from 2019-11-18 12-12-16](https://user-images.githubusercontent.com/40512816/69078196-f41a6300-09fc-11ea-8517-c1805720d86b.png)
![Screenshot from 2019-11-18 12-12-24](https://user-images.githubusercontent.com/40512816/69078197-f41a6300-09fc-11ea-930c-50b3621d55ca.png)
![Screenshot from 2019-11-18 12-14-17](https://user-images.githubusercontent.com/40512816/69078198-f41a6300-09fc-11ea-8f7b-757498a35b67.png)
