### ISSUE TITLE
Google Earth Crashes #2

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#407]
Google Earth Crashes in the background when I click `Show in Google Eatrh` in Workbench Data Set

I don't think it is related to #391

12:50:21 ERROR ui.tmanfe.SpreadSheet$3:369 - Grabbed the event as input
12:50:49  INFO subpane.wb.WorkbenchPaneSS:3140 - Showing map of selected records
12:50:55  INFO specify.rstools.GoogleEarthExporter:145 - Exporting data list
12:50:55  INFO specify.rstools.GoogleEarthExporter:158 - Writing KML output to /tmp/sp6export6624033139933951556.kmz
Gtk-Message: 12:50:56.693: Failed to load module "canberra-gtk-module"
12:50:57  WARN specify.rstools.GoogleEarthExporter:174 - Failed to open external viewer (e.g. Google Earth) for KML file
java.io.IOException: Failed to show URI:file:/tmp/sp6export6624033139933951556.kmz
	at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:123)
	at sun.awt.X11.XDesktopPeer.open(XDesktopPeer.java:86)
	at java.awt.Desktop.open(Desktop.java:269)
	at edu.ku.brc.util.AttachmentUtils.openFile(AttachmentUtils.java:331)
	at edu.ku.brc.specify.rstools.GoogleEarthExporter.openExternalViewer(GoogleEarthExporter.java:635)
	at edu.ku.brc.specify.rstools.GoogleEarthExporter.processDataList(GoogleEarthExporter.java:170)
	at edu.ku.brc.specify.tasks.PluginsTask.doProcessTool(PluginsTask.java:455)
	at edu.ku.brc.specify.tasks.PluginsTask.processToolDataFromList(PluginsTask.java:417)
	at edu.ku.brc.specify.tasks.PluginsTask.processToolList(PluginsTask.java:617)
	at edu.ku.brc.specify.tasks.PluginsTask.doCommand(PluginsTask.java:693)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.showRecordsInGoogleEarth(WorkbenchPaneSS.java:3220)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$13$1.run(WorkbenchPaneSS.java:693)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

![Screenshot from 2019-11-18 12-53-09](https://user-images.githubusercontent.com/40512816/69080916-83764500-0a02-11ea-8043-756eea153069.png)
![Screenshot from 2019-11-18 12-53-15](https://user-images.githubusercontent.com/40512816/69080917-83764500-0a02-11ea-8166-b758f3f74f16.png)
![Screenshot from 2019-11-18 12-53-25](https://user-images.githubusercontent.com/40512816/69080919-83764500-0a02-11ea-8bf8-dacc7991e050.png)
![Screenshot from 2019-11-18 12-53-39](https://user-images.githubusercontent.com/40512816/69080920-83764500-0a02-11ea-8904-06ef90ee51c1.png)
![Screenshot from 2019-11-18 12-53-44](https://user-images.githubusercontent.com/40512816/69080921-83764500-0a02-11ea-9612-bb079495e788.png)

**Comment by timo11** [comment]
Unable to duplicate.
Don't if the fake data might have something to do with it.
This might fix it: https://github.com/MajeurAndroid/Adb-Remote-Screen/issues/14

**Comment by maxxxxxdlp** [comment]
Unable to replicate myself again. Closing the issue
