### ISSUE TITLE
Java Error - null identifier in Accesion

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#409]
Java Error when trying to click on a Collection Object while entering new Accession

<img width="1552" alt="Screen Shot 2019-11-19 at 4 19 28 PM" src="https://user-images.githubusercontent.com/40512816/69191827-e2ae8500-0ae8-11ea-8c39-110d6753d2de.png">
<img width="1075" alt="Screen Shot 2019-11-19 at 4 19 22 PM" src="https://user-images.githubusercontent.com/40512816/69191828-e3471b80-0ae8-11ea-9ff6-bbe5b52413bc.png">

All Collection Objects where imported from a dataset and look identicly to the one on this screenshot:
<img width="1552" alt="Screen Shot 2019-11-19 at 4 20 00 PM" src="https://user-images.githubusercontent.com/40512816/69191710-a844e800-0ae8-11ea-8cc3-8d8c3fab1414.png">

Error is likely to be due to the fact that there is no value in some mandatory fields. In such case, there should be a non-null default value used

```
class_name: edu.ku.brc.af.ui.forms.TableViewObj
comments: 

stack_trace: 
org.hibernate.AssertionFailure: null identifier
	at org.hibernate.engine.EntityKey.<init>(EntityKey.java:39)
	at org.hibernate.event.def.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:74)
	at org.hibernate.event.def.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:39)
	at org.hibernate.impl.SessionImpl.fireRefresh(SessionImpl.java:902)
	at org.hibernate.impl.SessionImpl.refresh(SessionImpl.java:886)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.refresh(HibernateDataProviderSession.java:147)
	at edu.ku.brc.af.ui.forms.validation.ValComboBoxFromQuery.setValue(ValComboBoxFromQuery.java:1494)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUIComp(FormViewObj.java:5773)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5289)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4938)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4783)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4369)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.setData(ViewBasedDisplayPanel.java:339)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.setData(ViewBasedDisplayDialog.java:439)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1149)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1034)
	at edu.ku.brc.af.ui.forms.TableViewObj$7.mouseClicked(TableViewObj.java:830)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Interactions
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16e66f6e1b0
os_name: Mac OS X
os_version: 10.15.1
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2832571592
user_name: mambo
ip: 10.107.154.41
app_version: 6.8.00
collection: Collection
discipline: Botany
division: Division
institution: Institution
Collection_number: 1573858325.9892
Discipline_number: 1573858325.6325
Division_number: 1573858325.2985
Institution_number: 1573858318.8923
email: email@email.email
```

**Comment by maxxxxxdlp** [comment]
Probably error occurs because there is no catalog number
In such case user should receive a warning or Specify should handle error on its own
<img width="1068" alt="Screen Shot 2019-11-19 at 4 25 35 PM" src="https://user-images.githubusercontent.com/40512816/69192035-61a3bd80-0ae9-11ea-814a-abc6404a4f9e.png">

**Comment by maxxxxxdlp** [comment]
Same issue when editing **existing** Accesion that has one Collection Object **with** Catalog number

<img width="1068" alt="Screen Shot 2019-11-19 at 4 33 14 PM" src="https://user-images.githubusercontent.com/40512816/69192543-6d43b400-0aea-11ea-8c7d-1e8f0181b210.png">


And Collection Object fields:
<img width="1552" alt="Screen Shot 2019-11-19 at 4 34 37 PM" src="https://user-images.githubusercontent.com/40512816/69192590-8187b100-0aea-11ea-88c2-52601fb7cfc2.png">

**Comment by maxxxxxdlp** [comment]
There also are other error messages in log, May be related

![Screen Shot 2019-11-19 at 4 36 44 PM](https://user-images.githubusercontent.com/40512816/69192736-d3c8d200-0aea-11ea-9b5b-2b2a0fb1188f.png)

ok
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
16:34:30  WARN brc.ui.UIRegistry:533 - Couldn't find key[Save] in resource bundle [resources]
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination'.
The field '8' (qualifier) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '9' (addendum) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '11' (nameUsage) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
The field '12' (remarks) is hidden in the schema and shouldn't used on the Form 'Determination Table'.
16:36:12 DEBUG specify.dbsupport.HibernateDataProviderSession:146 - 1909924689
16:36:12 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: null identifier

**Comment by beach53** [comment]
Max will test more databases

**Comment by maxxxxxdlp** [comment]
Still the case
New botany database, was created in Specify 6.8
Collection objects were created thought a new Data Set in the Workbench and after uploading them into the table, I create a new dataset and then use it when creating new Accession in Interactions. In Accession data input window, double click on any of the Collection Objects causes an error

<img width="1440" alt="Screen Shot 2019-12-04 at 1 28 21 PM" src="https://user-images.githubusercontent.com/40512816/70174123-f2f26280-1699-11ea-8f93-a212ae942d7f.png">
<img width="1440" alt="Screen Shot 2019-12-04 at 1 28 56 PM" src="https://user-images.githubusercontent.com/40512816/70174191-0bfb1380-169a-11ea-8e4c-a7836728f81e.png">
<img width="1440" alt="Screen Shot 2019-12-04 at 1 28 32 PM" src="https://user-images.githubusercontent.com/40512816/70174139-f8e84380-1699-11ea-9252-c18ff3e6096b.png">

Same issue if I add even more Collection Objects from a record
<img width="1440" alt="Screen Shot 2019-12-04 at 1 33 33 PM" src="https://user-images.githubusercontent.com/40512816/70174504-ad826500-169a-11ea-8cbd-4c2af9c8466b.png">

Don't know if it is related, but the `Save` button does not work. Does not save new Accessions and does not save changes to existing accessions
<img width="1440" alt="Screen Shot 2019-12-04 at 1 36 56 PM" src="https://user-images.githubusercontent.com/40512816/70174767-25508f80-169b-11ea-9967-3da902f8a1bb.png">

class_name: edu.ku.brc.af.ui.forms.TableViewObj
comments: 

stack_trace: 
org.hibernate.AssertionFailure: null identifier
	at org.hibernate.engine.EntityKey.<init>(EntityKey.java:39)
	at org.hibernate.event.def.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:74)
	at org.hibernate.event.def.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:39)
	at org.hibernate.impl.SessionImpl.fireRefresh(SessionImpl.java:902)
	at org.hibernate.impl.SessionImpl.refresh(SessionImpl.java:886)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.refresh(HibernateDataProviderSession.java:147)
	at edu.ku.brc.af.ui.forms.validation.ValComboBoxFromQuery.setValue(ValComboBoxFromQuery.java:1494)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUIComp(FormViewObj.java:5773)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5289)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4938)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4783)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4369)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.setData(ViewBasedDisplayPanel.java:339)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.setData(ViewBasedDisplayDialog.java:439)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1149)
	at edu.ku.brc.af.ui.forms.TableViewObj.editRow(TableViewObj.java:1034)
	at edu.ku.brc.af.ui.forms.TableViewObj$7.mouseClicked(TableViewObj.java:830)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Interactions
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16ec90b5750
os_name: Mac OS X
os_version: 10.15.1
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2861919784
user_name: mambo
ip: 10.107.154.41
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1574890422.4166
Discipline_number: 1574890422.1656
Division_number: 1574890421.8124
Institution_number: 1574890415.3712
email: 1

**Comment by timo11** [comment]
This only happens for me when the Accession is in edit mode, and has been changed. The source of the collectionobjects is irrelevent. It happens when the Accession ComboBox in the CollectionObject form is set. 
There seems to be no mechanism for telling a DisplayDialog what DataObject's form it was initiated from. The Accession ComboBox pretty much cannot be editable on the CO display dialog form if it is opened from an Accession in edit mode. 
(I'm not sure it's a good idea to make the CO popup dialog editable, in general.)
This can be fixed by removing the table view for COs, as was done on the CE form (making it impossible to see more than one CO at a time), or to make the table view read only if possible.
Another option is to make a new CollectionObjectDialog form w Accession, Project, Containers, and probably CE disabled.

**Comment by timo11** [comment]
The collectionobject form will no longer pop up when the accession form is in edit mode. 
This is enforced in the AccessionBusRules.
Another way to get the same effect for other cases is to do something like this:

**Comment by maxxxxxdlp** [comment]
Still happens. Did I do something wrong?

![Screenshot from 2020-02-10 14-00-33](https://user-images.githubusercontent.com/40512816/74185190-c1ec5c00-4c0d-11ea-9077-99b6b4f1eff5.png)

The latest build of `develop`'s branch (Specify 6.8)
Newly created Botany database
Ubuntu 18.04 (not in a VM)
MySQL 5.7
Amazon Corretto 8

**Comment by maxxxxxdlp** [comment]
Latest build here
Uncommented the following line:

![Screenshot from 2020-02-10 17-04-59](https://user-images.githubusercontent.com/40512816/74198620-7e065080-4c27-11ea-894c-d0faeac9640d.png)

Recreated the database
Now, nothing happens when I double click on the CO line. Did you make any changes to the code in a meanwhile?

Here is the complete log:
[log.txt](https://github.com/specify/specify6/files/4183481/log.txt)
