### ISSUE TITLE
SpBackupRestore window not closing

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#417]
After backing up or restoring the database, SpBackupRestore window does not close.
The issue occurred on 6.7.04 and 6.8. Backup completes successfully and controls elements inside the window remain responsive, but the window can not be closed.

The probable reason is that the window was made unclosable when database backup or restore begun, but the Event to signal for the window to get closable again was not Triggered.

The issue does not always happen. Does not seem to be connected to a specific database / Specify version / Backup location

Tried to close the window through:
Clicking on Red Cross
Pressing ^C in console
Making in Quit thought button on the taskbar

May be connected to #397, except in that case, window is closable by clicking the `Close` button inside the window. SpBackupRestore does not have the `Close` button inside

The issue occurred on Linux (maybe connected with the computer being not powerful enough)

Will add more information after further testing

**Comment by maxxxxxdlp** [comment]
![Screenshot from 2019-11-20 12-55-32](https://user-images.githubusercontent.com/40512816/69285032-98dfa080-0bb5-11ea-9c96-4c94ec437f45.png)

**Comment by maxxxxxdlp** [comment]
Same problem with SpecifyL10N on macOS. Windows not closing when clicking on the red cross or Task Bar>Quit. Even thoug the window did close after ^C in console

Noticed that the window does close perfectly normally, until I click somewhere inside of it.

Specify 6.8

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.ku.brc.specify.tools.StrLocalizerApp.checkForChanges(StrLocalizerApp.java:1580)
	at edu.ku.brc.specify.tools.StrLocalizerApp.windowClosing(StrLocalizerApp.java:1790)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

<img width="1440" alt="Screen Shot 2019-11-22 at 9 07 24 AM" src="https://user-images.githubusercontent.com/40512816/69436709-82495e80-0d07-11ea-921d-41a2d45247bd.png">
<img width="1440" alt="Screen Shot 2019-11-22 at 9 07 15 AM" src="https://user-images.githubusercontent.com/40512816/69436715-85444f00-0d07-11ea-953b-ebc732124088.png">
<img width="1440" alt="Screen Shot 2019-11-22 at 9 07 11 AM" src="https://user-images.githubusercontent.com/40512816/69436716-85444f00-0d07-11ea-89b8-c317f68832fb.png">

**Comment by beach53** [comment]
Tim to research best remedy

**Comment by maxxxxxdlp** [comment]
One more window that can not be closed throught the red button at the top right corner, even thoug the button is active. The button should be dissabled, removed or given it's action back, as current solution is very confusing.
<img width="1440" alt="Screen Shot 2019-12-09 at 9 45 29 AM" src="https://user-images.githubusercontent.com/40512816/70450088-bb543380-1a68-11ea-85dc-5f88ffab4fcd.png">

**Comment by maxxxxxdlp** [comment]
Removed some cases from this issue and moved them to #397 
This issue implies that the window can not be closed in any way and that is caused by a bug of some sort after user performed an action
Issues shown in #397 happen every time, on every platform and do not require much from the user to reproduce them
