### ISSUE TITLE
Register crashes

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#420]
The program called **Register** (`./Specify/bin/Register`) crashes on macOS and Linux

### Log:

```
This launcher was created with an evaluation version of install4j.
14:26:05 DEBUG brc.ui.UIRegistry:676 - Working Path not set, setting it to[/home/m001p596/Specify_6_8_00_3/bin]
14:26:05 DEBUG brc.helpers.XMLHelper:190 - Checking Working Path[/home/m001p596/Specify_6_8_00_3/bin/config]
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Couldn't find config path[/home/m001p596/Specify_6_8_00_3/bin/config]
	at edu.ku.brc.helpers.XMLHelper.getConfigDirPath(XMLHelper.java:193)
	at edu.ku.brc.helpers.XMLHelper.getConfigDir(XMLHelper.java:210)
	at edu.ku.brc.ui.IconManager.loadIcons(IconManager.java:383)
	at edu.ku.brc.ui.IconManager.setApplicationClass(IconManager.java:146)
	at edu.ku.brc.specify.utilapps.RegisterApp$12.run(RegisterApp.java:1585)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![Screenshot from 2019-11-22 14-27-08](https://user-images.githubusercontent.com/40512816/69458090-31039400-0d34-11ea-98f1-ab9263a20d45.png)

**Comment by beach53** [comment]
not distributed donot fix
