### ISSUE TITLE
Java Exception when editing users

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#446]
Path to replicate this bug:
Specify 6.8 latest beta on macOS. Using Botany database created in Specify 6.8 with only a few rows of data in every table
Security Tools > removed all permissions for `Guest` users. Without saving clicked on `Add new user to Group`.
Specify all the data for new user and generate a key
When asked whether to create or search for an agent, choose `Search`
Find and select an agent
Click ok
Exception fired, new user created but guest group settings not saved

<img width="1075" alt="Screen Shot 2019-12-04 at 10 27 09 AM" src="https://user-images.githubusercontent.com/40512816/70160798-b108f280-1680-11ea-90cc-5761127b777c.png">

<img width="1552" alt="Screen Shot 2019-12-04 at 10 27 14 AM" src="https://user-images.githubusercontent.com/40512816/70160772-a51d3080-1680-11ea-9eef-fc440b7849d5.png">

Here is how the attached agent looks:
<img width="1552" alt="Screen Shot 2019-12-04 at 10 33 53 AM" src="https://user-images.githubusercontent.com/40512816/70161368-92efc200-1681-11ea-9136-16fc5258b7f7.png">

class_name: edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane
comments: 

stack_trace: 
edu.ku.brc.dbsupport.StaleObjectException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:224)
	at edu.ku.brc.specify.tasks.subpane.security.AdminInfoSubPanelWrapper.savePermissionData(AdminInfoSubPanelWrapper.java:399)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.doSave(SecurityAdminPane.java:1197)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.showInfoPanel(SecurityAdminPane.java:964)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.access$600(SecurityAdminPane.java:113)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane$2.valueChanged(SecurityAdminPane.java:368)
	at javax.swing.JTree.fireValueChanged(JTree.java:2934)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1641)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeMgr.addNewUser(NavigationTreeMgr.java:764)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeContextMenuMgr$1.actionPerformed(NavigationTreeContextMenuMgr.java:102)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:261)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:120)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	... 52 more

task_name: SecurityAdmin
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16ec90b5750
os_name: Mac OS X
os_version: 10.15.1
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3415261328
user_name: mambo
ip: 10.107.154.41
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1574890422.4166
Discipline_number: 1574890422.1656
Division_number: 1574890421.8124
Institution_number: 1574890415.3712
email: 1

Comment, if more information is needed or unable to replicate

**Comment by maxxxxxdlp** [comment]
I have narrowed down the replication steps for this bug:
Make any changes to the permission of any group of users (Guests, Limited, ...)
Press on `Add New User to Group`
Create User
Find/Create an agent for this user
Save changes

If I change the `Name` or `Remarks` fields, I also get asked wheter to save changes for `Security Tools`
<img width="844" alt="Screen Shot 2019-12-31 at 11 13 01 AM" src="https://user-images.githubusercontent.com/40512816/71628641-84cc8d00-2bbe-11ea-9480-442aa5652943.png">
<img width="585" alt="Screen Shot 2019-12-31 at 11 09 56 AM" src="https://user-images.githubusercontent.com/40512816/71628627-6ebecc80-2bbe-11ea-8b8f-f9b2c8dd4985.png">

Stack trace at this point:
```
class_name: edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane	
comments: 	
stack_trace: 	
edu.ku.brc.dbsupport.StaleObjectException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]	
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:224)	
	at edu.ku.brc.specify.tasks.subpane.security.AdminInfoSubPanelWrapper.savePermissionData(AdminInfoSubPanelWrapper.java:399)	
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.doSave(SecurityAdminPane.java:1197)	
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.aboutToShutdown(SecurityAdminPane.java:1297)	
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane$2.valueChanged(SecurityAdminPane.java:288)	
	at javax.swing.JTree.fireValueChanged(JTree.java:2934)	
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)	
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)	
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)	
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)	
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)	
	at javax.swing.JTree.setSelectionPath(JTree.java:1641)	
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeMgr.addNewUser(NavigationTreeMgr.java:764)	
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeContextMenuMgr$1.actionPerformed(NavigationTreeContextMenuMgr.java:102)	
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)	
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)	
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)	
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)	
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)	
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)	
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)	
	at java.awt.Component.processMouseEvent(Component.java:6539)	
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)	
	at java.awt.Component.processEvent(Component.java:6304)	
	at java.awt.Container.processEvent(Container.java:2239)	
	at java.awt.Component.dispatchEventImpl(Component.java:4889)	
	at java.awt.Container.dispatchEventImpl(Container.java:2297)	
	at java.awt.Component.dispatchEvent(Component.java:4711)	
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)	
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)	
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)	
	at java.awt.Container.dispatchEventImpl(Container.java:2283)	
	at java.awt.Window.dispatchEventImpl(Window.java:2746)	
	at java.awt.Component.dispatchEvent(Component.java:4711)	
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)	
	at java.awt.EventQueue.access$500(EventQueue.java:97)	
	at java.awt.EventQueue$3.run(EventQueue.java:709)	
	at java.awt.EventQueue$3.run(EventQueue.java:703)	
	at java.security.AccessController.doPrivileged(Native Method)	
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)	
	at java.awt.EventQueue$4.run(EventQueue.java:733)	
	at java.awt.EventQueue$4.run(EventQueue.java:731)	
	at java.security.AccessController.doPrivileged(Native Method)	
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)	
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)	
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)	
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)	
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)	
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)	
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)	
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]	
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:261)	
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:120)	
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)	
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)	
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)	
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)	
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)	
	... 51 more	
task_name: SecurityAdmin	
title: 	
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16f258254c0	
os_name: Mac OS X	
os_version: 10.15.2	
java_version: 1.8.0_232	
java_vendor: Amazon.com Inc.	
max_memory: 3817865216	
used_memory: 3423335384	
user_name: mambo	
ip: 10.107.154.41	
app_version: 6.8.00	
collection: 1	
discipline: Invertebrate Paleontology	
division: 1	
institution: 1	
Collection_number: 1577124550.8173	
Discipline_number: 1577124550.4786	
Division_number: 1577485769.2396	
Institution_number: 1577124543.7762	
email: 1
```

And then I get asked whether to save changes for an idividual group
<img width="624" alt="Screen Shot 2019-12-31 at 11 10 03 AM" src="https://user-images.githubusercontent.com/40512816/71628628-6ebecc80-2bbe-11ea-814c-87bce4081fa5.png">

Stack trace at this point (similar one):
```
class_name: edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane
comments: 

stack_trace: 
edu.ku.brc.dbsupport.StaleObjectException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:224)
	at edu.ku.brc.specify.tasks.subpane.security.AdminInfoSubPanelWrapper.savePermissionData(AdminInfoSubPanelWrapper.java:399)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.doSave(SecurityAdminPane.java:1197)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.showInfoPanel(SecurityAdminPane.java:964)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.access$600(SecurityAdminPane.java:113)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane$2.valueChanged(SecurityAdminPane.java:368)
	at javax.swing.JTree.fireValueChanged(JTree.java:2934)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1641)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeMgr.addNewUser(NavigationTreeMgr.java:764)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeContextMenuMgr$1.actionPerformed(NavigationTreeContextMenuMgr.java:102)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpPrincipal#2]
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:261)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:120)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	... 52 more

task_name: SecurityAdmin
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16f258254c0
os_name: Mac OS X
os_version: 10.15.2
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3435794008
user_name: mambo
ip: 10.107.154.41
app_version: 6.8.00
collection: 1
discipline: Invertebrate Paleontology
division: 1
institution: 1
Collection_number: 1577124550.8173
Discipline_number: 1577124550.4786
Division_number: 1577485769.2396
Institution_number: 1577124543.7762
email: 1

```

**Comment by maxxxxxdlp** [comment]
Also, when I add an existing user to the user group, I get the following error: (regardless of me making or saving changes to the user group)

```
class_name: edu.ku.brc.specify.tasks.subpane.security.NavigationTreeMgr
comments: 

stack_trace: 
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [edu.ku.brc.specify.datamodel.SpecifyUser#9]
	at org.hibernate.impl.SessionFactoryImpl$1.handleEntityNotFound(SessionFactoryImpl.java:377)
	at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:145)
	at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:179)
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:103)
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:878)
	at org.hibernate.impl.SessionImpl.internalLoad(SessionImpl.java:846)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:557)
	at org.hibernate.type.EntityType.resolve(EntityType.java:379)
	at org.hibernate.type.EntityType.replace(EntityType.java:259)
	at org.hibernate.type.CollectionType.replaceElements(CollectionType.java:451)
	at org.hibernate.type.CollectionType.replace(CollectionType.java:518)
	at org.hibernate.type.TypeFactory.replace(TypeFactory.java:482)
	at org.hibernate.event.def.DefaultMergeEventListener.copyValues(DefaultMergeEventListener.java:340)
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:267)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:120)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeMgr.addExistingUser(NavigationTreeMgr.java:864)
	at edu.ku.brc.specify.tasks.subpane.security.NavigationTreeContextMenuMgr$2.actionPerformed(NavigationTreeContextMenuMgr.java:111)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: SecurityAdmin
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--16f258254c0
os_name: Mac OS X
os_version: 10.15.2
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3494323056
user_name: mambo
ip: 10.107.154.41
app_version: 6.8.00
collection: 1
discipline: Invertebrate Paleontology
division: 1
institution: 1
Collection_number: 1577124550.8173
Discipline_number: 1577124550.4786
Division_number: 1577485769.2396
Institution_number: 1577124543.7762
email: 1
```
