### ISSUE TITLE
Corrupt database if not finished Setup it in SpWizzard

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#457]
After creating new database in Specify Wizzard, it asks for information like institution name and agent info. At this point the dataabase is created, yet not setted up entirely. If user clicks on the button to cancel the database setup and tries to log into it, Specify would show the following error:

```
class_name: edu.ku.brc.specify.config.AppPrefsGlobalDBIOIImpl
comments: 

stack_trace: 
java.lang.RuntimeException: No context has been set.
	at edu.ku.brc.af.core.AppContextMgr.getClassObject(Unknown Source)
	at edu.ku.brc.specify.datamodel.SpAppResourceDir.initialize(Unknown Source)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.getAppResDir(Unknown Source)
	at edu.ku.brc.specify.config.AppPrefsGlobalDBIOIImpl.createResDir(Unknown Source)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.load(Unknown Source)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.exists(Unknown Source)
	at edu.ku.brc.af.prefs.AppPreferences.load(Unknown Source)
	at edu.ku.brc.af.prefs.AppPreferences.get(Unknown Source)
	at edu.ku.brc.af.prefs.AppPreferences.get(Unknown Source)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(Unknown Source)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(Unknown Source)
	at edu.ku.brc.af.core.db.MySQLBackupService.checkForBackUp(Unknown Source)
	at edu.ku.brc.specify.Specify.doExit(Specify.java:2393)
	at edu.ku.brc.specify.Specify.doCommand(Specify.java:3252)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(Unknown Source)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.updateSchema(SpecifySchemaUpdateService.java:459)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.doLoginContinuing2(Unknown Source)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17$2.exited(Unknown Source)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.exited(Unknown Source)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.run(Unknown Source)

task_name: 
title: 
id: 767063a4-c0ee-ec40-ebcd-acca3a334ef5--163463860d0
os_name: Linux
os_version: 5.0.0-37-generic
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3106695112
user_name: m001p596
ip: 127.0.0.1
app_version: 6.7.01
```

Tested in 6.7.01, but I would suspect that it is also reproducable in 6.8
The database should be deleted, if user cancels the setup process, or he should be faced with a proper error message when trying to log into this database

**Comment by maxxxxxdlp** [comment]
Also, user gets an empty error message afterwards and the program closes. See #437

**Comment by maxxxxxdlp** [comment]
Database can be restored to working order, if manager restores database from a `.sql` file
