### ISSUE TITLE
Specify is unable to create the `master` account

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#479]
When creating a new database in Specify on macOS, I receive an error message notifying me about Specify being unable to create the `master` user

![Screen Shot 2019-12-27 at 8 29 14 AM](https://user-images.githubusercontent.com/40512816/71524611-22545380-2883-11ea-88dd-237fb93d4934.png)

The issue can be solved by ignoring the error message (closing it) and clicking on the `Create Master User` again

Issue seem to happen only one time for the first database

Happens on macOs 10.14 and 10.13 with Amazon Correto 8 and **MySQL 5.7**

**Comment by maxxxxxdlp** [comment]
Happened in Ubuntu 19.10

![Screenshot from 2020-01-02 13-42-10](https://user-images.githubusercontent.com/40512816/71695177-30641180-2d66-11ea-9b52-ae4d21cb9ee3.png)

**Comment by maxxxxxdlp** [comment]
Happened in Windows 10 1909

**Comment by maxxxxxdlp** [comment]
Seems to happen only once for the first SpWizzard database

**Comment by maxxxxxdlp** [comment]
It seems to happen only for MySQL. Not for MariaDB

**Comment by maxxxxxdlp** [comment]
![Screen Shot 2020-04-13 at 12 02 28 PM](https://user-images.githubusercontent.com/40512816/79141112-c1dc1a00-7d7e-11ea-8fb9-ba6e5d5a31f1.png)

Happened again
Mac Mini (not in VM)
macOS 10.15
MySQL 5.7

**Comment by timo11** [comment]
Please attach the Specify log files? 
Also, if/when this problem is repeatable, running the wizard from the command line might reveal helpful information.

**Comment by maxxxxxdlp** [comment]
As far as I noticed, it happens 50% of the time when installing Specify on a machine that did not have Specify before. Seems to happen for all OS, but only for MySQL

I will try to replicate it today

**Comment by norinespears** [comment]
Didn't we have this happen when the Master was named 'master' back in the early days of Specify? I seem to remember that it is the reason that I was asked to add this line to the documentation: "When creating the Master username and password, the word "Master" or "Root" SHOULD NOT BE USED."

**Comment by maxxxxxdlp** [comment]
Here is the exception:
```
11:40:22 DEBUG brc.ui.UIHelper:1647 - try login
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON specify.* TO 'master'@'localhost'' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at edu.ku.brc.dbsupport.MySQLDMBSUserMgr.createUser(MySQLDMBSUserMgr.java:1461)
	at edu.ku.brc.specify.config.init.MasterUserPanel$5.doInBackground(MasterUserPanel.java:489)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
11:40:28 ERROR brc.ui.UIRegistry:1187 - <html>The wizard was unable to create the 'master' account for Specify.<br>Are you logged in as root?
```


In case this is not enough information, here is the full log: 
[full_log.html.zip](https://github.com/specify/specify6/files/4477111/full_log.html.zip)

**Comment by maxxxxxdlp** [comment]
@timo11 If you can't figure out the cause of this problem, you can send me a build of Specify that logs more useful information and I can test in on a VM restored from a snapshot

**Comment by timo11** [comment]
This was caused by a really dumb typo. Which for some reason only some mysql entities cared about, and even when they did the create command succeeded. 

Anyway, It is a one line, highly safe fix.
