### ISSUE TITLE
Unable to create database after migrating to MariaDB

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify6#480]
I have installed MySQL 5.7 along with Amazon Correto 8 and Specify 6.8 (12/20) on macOS 10.14 (VM) and created a database

Then I uninstalled MySQL and Installed MariaDB 10.14 and am no longer able to log in into the database

Then I tried to recreate the database with the same name thought SpWizard

I have received this error message:
![Screen Shot 2019-12-27 at 9 35 41 AM](https://user-images.githubusercontent.com/40512816/71526563-5e3fe680-288c-11ea-9f33-5977b97e7128.png)

This is the console output:
![Screen Shot 2019-12-27 at 9 29 41 AM](https://user-images.githubusercontent.com/40512816/71526481-01dcc700-288c-11ea-81aa-a5fca98e86f3.png)

and this:
![Screen Shot 2019-12-27 at 9 34 37 AM](https://user-images.githubusercontent.com/40512816/71526517-318bcf00-288c-11ea-8747-e5861e2895cf.png)
```
org.hibernate.exception.GenericJDBCException: Cannot open connection
	at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:103)
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:91)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:426)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:139)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1547)
	at org.hibernate.loader.Loader.doQuery(Loader.java:673)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.doList(Loader.java:2220)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
	at org.hibernate.loader.Loader.list(Loader.java:2099)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:378)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:338)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:172)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1121)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:79)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.getDataList(HibernateDataProviderSession.java:241)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.getAppResDir(SpecifyAppContextMgr.java:792)
	at edu.ku.brc.specify.config.AppPrefsGlobalDBIOIImpl.createResDir(AppPrefsGlobalDBIOIImpl.java:51)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.load(AppPrefsDBIOIImpl.java:165)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.exists(AppPrefsDBIOIImpl.java:106)
	at edu.ku.brc.af.prefs.AppPreferences.load(AppPreferences.java:751)
	at edu.ku.brc.af.prefs.AppPreferences.get(AppPreferences.java:398)
	at edu.ku.brc.af.prefs.AppPreferences.get(AppPreferences.java:384)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(AppPreferences.java:494)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(AppPreferences.java:511)
	at edu.ku.brc.af.core.db.MySQLBackupService.checkForBackUp(MySQLBackupService.java:1254)
	at edu.ku.brc.specify.Specify.doExit(Specify.java:2257)
	at edu.ku.brc.af.core.MacOSAppHandler$3.handleQuitRequestWith(MacOSAppHandler.java:60)
	at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:395)
	at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:388)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.hibernate.connection.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:56)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	... 43 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 46 more
```

**Comment by grantfitzsimmons** [comment]
I don't believe this has been recreated since, but please feel free to reopen if so @maxpatiiuk 
We use MariaDB 10.11 to create databases often now
