### ISSUE TITLE
Java Exception When Saving Changes to CO

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#483]
I am testing how Specify works with MariaDB
I have created a collection object and after saving it, went on to edit it. Then when I tried to save my changes I received the following error messages:

![Screenshot (2)](https://user-images.githubusercontent.com/40512816/71532222-f99a8100-28b7-11ea-8e31-cb1e3140a1d2.png)

![Screenshot (3)](https://user-images.githubusercontent.com/40512816/71532259-25b60200-28b8-11ea-88d1-41cc5f37476d.png)

Happens even after I reboot the Specify
Seems not to depend on the fields I have edited
Specify continues to work normally after this error, except I can not save changes

```
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.CollectionObject.dnaSequences, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.addExtraObjectForProcessing(CollectionObjectBusRules.java:653)
	at edu.ku.brc.specify.datamodel.busrules.AttachmentOwnerBaseBusRules.beforeMerge(AttachmentOwnerBaseBusRules.java:111)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.beforeMerge(CollectionObjectBusRules.java:591)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2857)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3084)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:883)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Specify 6.8 (12/20)
**MariaDB 10.14**
Windows 10
Amazon Correto 8
Clean database

**Comment by maxxxxxdlp** [comment]
Seems to happen only with Collection Object table

**Comment by yvonneekanim** [comment]
I'm getting the same error message on my PC

**Comment by maxxxxxdlp** [comment]
Still happens
The user just needs to press "Save" in any existing CO for the exception to get triggered
Happens even if not edited any fields
Happens on macOS, Windows, and Linux only with MariaDB

Tested in fresh botany databases
Even though the error mentions something about DNA, I do not see any fields regarding DNA on the default CO view

**Comment by timo11** [comment]
Never happens for me. 
What is the current stack trace for the exception? The code has changed a lot since 12/20.

**Comment by maxxxxxdlp** [comment]
```
class_name: edu.ku.brc.af.ui.forms.FormViewObj
comments: 

stack_trace: 
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.CollectionObject.dnaSequences, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.addExtraObjectForProcessing(CollectionObjectBusRules.java:653)
	at edu.ku.brc.specify.datamodel.busrules.AttachmentOwnerBaseBusRules.beforeMerge(AttachmentOwnerBaseBusRules.java:111)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.beforeMerge(CollectionObjectBusRules.java:591)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2857)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3084)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:883)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Data_Entry
title: 
id: ae7f7424-0c8f-2a72-6a5c-beb4b1ac3d63--16f258254c0
os_name: Mac OS X
os_version: 10.15
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 3034754496
user_name: specify
ip: 192.168.2.135
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1577988803.2427
Discipline_number: 1577988802.8297
Division_number: 1577988800.9796
Institution_number: 1577988793.7839
email: 1
```

**Comment by timo11** [comment]
That's not the current code.

**Comment by maxxxxxdlp** [comment]
My bet,
@timo11 You are right,
I forgot to update my Specify on a VM
The bug does not seem to happen any longer in the latest version
@yvonneekanim can you also confirm that this is fixed?

**Comment by yvonneekanim** [comment]
I don't get the error anymore

**Comment by maxxxxxdlp** [comment]
I noticed that I reported it twice (#581) and @timo11 fixed it in there
