### ISSUE TITLE
BE: erroneous mapping requirement

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#5]
For the attached query, I am unable to use the Batch Editor function without adding the field CO.text1, which doesn't seem to make any sense. I also get the error below.

![batcheditorerror](https://user-images.githubusercontent.com/12533028/33580986-c59288e8-d914-11e7-9f07-0e00a69d1aad.png)

[BatchEditorQueryIssue.zip](https://github.com/specify/specify6/files/1529105/BatchEditorQueryIssue.zip)

class_name: edu.ku.brc.specify.tasks.WorkbenchTask
comments: 

stack_trace: 
java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.buildValidator(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.buildValidator(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.<init>(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.doIt(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.access$100(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

task_name: BatchEdit
title: 
id: fa341824-173a-0988-6119-3b90cafcd922--16009a747b0
os_name: Windows 7
os_version: 6.1
java_version: 1.8.0_152
java_vendor: Oracle Corporation
max_memory: 778502144
used_memory: 423004944
user_name: g778g663
ip: 169.254.88.15
app_version: 6.6.06
collection: CReAC
discipline: Entomology
division: Entomology
institution: KU Biodiversity Institute
Collection_number: 1337872530.67
Discipline_number: 1337872530.34
Division_number: 1337872530
Institution_number: 1337872526.99
ISA_number: 2014548
email: scschmits@ku.edu

**Comment by timo11** [comment]
This is most likely happening because CollectionObject.Text1 is a required field in the schema.

It's kind of hard not to require it in the dataset, though in the 'main' upload table, to which no records will be added, it might be possible to ignore the requirement.
