### ISSUE TITLE
Java NullPointerException in BatchEdut

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#539]
I created a query that used a lot of related tables (CO, Accesions, Agents, Locality) and uploaded 7000 records into BatchEdit. After changing few thousand values and waiting for field validating, I closed the main Specify window without saving any changes. Then I have seen that the exception has occurred at some point and the window with error message was hidden behind the Specify window so have been unnoticed by me. So I am not sure which of my action has caused this bug.

If there would be need to provide more information, I can try to reproduce the error

Console log:
```
12:40:51 ERROR specify.tasks.WorkbenchTask:2106 - Couldn't find RolloverCommand for WorkbenchId [17]
12:40:51 ERROR af.core.ContextMgr:170 - Couldn't find task by class [SGRTask]
12:40:51  WARN hibernate.util.JDBCExceptionReporter:77 - SQL Error: 0, SQLState: null
12:40:51 ERROR hibernate.util.JDBCExceptionReporter:78 - An SQLException was provoked by the following failure: java.lang.InterruptedException
12:40:51  INFO brc.specify.Specify:2260 - Application shutdown
Warning: Could not get charToByteConverterClass!
12:40:51  INFO brc.specify.Specify:2281 - Successfully saved long term cache mapping
12:40:51  INFO brc.specify.Specify:2289 - Clearing the short term cache
12:40:51  INFO brc.specify.Specify:2296 - Successfully saved forms cache mapping
12:40:51 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.updateBtnUI(WorkbenchPaneSS.java:1578)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS$ValidationWorker$2.run(WorkbenchPaneSS.java:5333)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![Screenshot from 2020-01-10 12-41-26](https://user-images.githubusercontent.com/40512816/72184989-91af6480-33a6-11ea-9004-7828019e5bd7.png)

Specify 6.8 (12/20)
Ubuntu 19.10
Amazon Corretto 8
MySQL 5.7.28

**Comment by timo11** [comment]
It looks like the exception occurred after specify was closed because a validation thread tried to access a non-existent UI element. 
Most likely fix is to update okToShutdown method for the WorkbenchPane.
