### ISSUE TITLE
Tricky lat/lng text values cause export problems

### ISSUE THREAD

**Issue by timo11** [specify/specify6#54]
The lat/lng values in the cache table created by the exporter app sometimes are not in valid numeric formats when the exporter app gets confused by the values in the lat/lng text fields in the locality table.
This causes exception popups when exporting for the web portal, and junk data in aggregators like gbif.

**Comment by timo11** [comment]
One way to test this fix is to restore the vimsfish.sql.bz2 file in the Virginia I of MS folder in Conversion Databases on specify6. If you run the exporter app and try to export for web portal you should get an error. Then open the DB in specify and change and unchange the Web Portal schema mapping then save (to force the exporter to rebuild). Then open the exporter app and rebuild the cache. Export for web portal should work. 

Then use the exporter on a few other dbs to make sure it seems to be working decently.

**Comment by tlammer** [comment]
When I open the data exporter for VIMS, I get three errors immediately

java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Unknown Source)
	at java.util.Vector$Itr.next(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.qb.TableTree.clone(TableTree.java:239)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.fixAliases(QueryBldrPane.java:5180)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.getFieldQRI(QueryBldrPane.java:4561)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.getFieldQRI(QueryBldrPane.java:4590)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.getFieldQRI(QueryBldrPane.java:4590)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.getQueryFieldPanelsForMapping(QueryBldrPane.java:4755)
	at edu.ku.brc.specify.tools.export.ExportPanel.getSpecs(ExportPanel.java:1010)
	at edu.ku.brc.specify.tools.export.ExportPanel.retrieveMappingStatus(ExportPanel.java:1729)
	at edu.ku.brc.specify.tools.export.ExportPanel.retrieveMappingStatus(ExportPanel.java:1691)
	at edu.ku.brc.specify.tools.export.ExportPanel$19.doInBackground(ExportPanel.java:1771)
	at edu.ku.brc.specify.tools.export.ExportPanel$19.doInBackground(ExportPanel.java:1763)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)



java.lang.NullPointerException
	at edu.ku.brc.specify.tools.export.ExportPanel.getSpecs(ExportPanel.java:1044)
	at edu.ku.brc.specify.tools.export.ExportPanel.retrieveMappingStatus(ExportPanel.java:1729)
	at edu.ku.brc.specify.tools.export.ExportPanel.retrieveMappingStatus(ExportPanel.java:1691)
	at edu.ku.brc.specify.tools.export.ExportPanel$19.doInBackground(ExportPanel.java:1771)
	at edu.ku.brc.specify.tools.export.ExportPanel$19.doInBackground(ExportPanel.java:1763)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


java.lang.NullPointerException
	at edu.ku.brc.specify.tools.export.ExportPanel.displayStatusForMap(ExportPanel.java:809)
	at edu.ku.brc.specify.tools.export.ExportPanel$19$1.run(ExportPanel.java:1787)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by timo11** [comment]
It's been doing that for years. Just keep trying.

**Comment by timo11** [comment]
Or delete all the mappings but the Web Portal mapping.

**Comment by tlammer** [comment]
Tried again and it worked
