### ISSUE TITLE
Exception when creating a Data Set from Record Set

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#559]
Happens in Workbench when trying to `Create Data Set from Record Set` (after selecting the `Record Set` and specifying the name for the new `Data Set`, when the user presses on the `OK` button)

```
class_name: edu.ku.brc.specify.tasks.WorkbenchTask
comments: 

stack_trace: 
java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.loadRecordToWb(Uploader.java:6310)
	at edu.ku.brc.specify.tasks.WorkbenchTask.loadRsIntoWb(WorkbenchTask.java:1841)
	at edu.ku.brc.specify.tasks.WorkbenchTask$1.construct(WorkbenchTask.java:1911)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at java.lang.Thread.run(Thread.java:748)

task_name: Workbench
title: 
id: 3145e6c5-8b47-d376-afe3-6269ceca457a--16f258346f0
os_name: Linux
os_version: 5.3.0-24-generic
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2633928792
user_name: specify
ip: 127.0.1.1
app_version: 6.8.00
collection: 1
discipline: Herpetology
division: 1
institution: 1
Collection_number: 1575924181.0902
Discipline_number: 1575924180.7535
Division_number: 1575924180.5777
Institution_number: 1575924179.6843
email: 1

```

**Comment by maxxxxxdlp** [comment]
Seems to work well with different record set

![Screenshot from 2020-01-14 06-59-36](https://user-images.githubusercontent.com/40512816/72354985-7a6cc180-369b-11ea-940e-56c1845dcf04.png)

This record set, the one that works, is based on a data set already in Workbench
The record set that causes problems, its mapping is based on a query, which may be a source of this issue
![Screenshot from 2020-01-14 07-00-26](https://user-images.githubusercontent.com/40512816/72355129-b4d65e80-369b-11ea-8287-da4a72c4e45e.png)


Tested with MariaDB 10.4
