### ISSUE TITLE
Null pointer exception when trying to open Accession using Enter Catalog Numbers

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#57]
Click Accession in the sidebar to open an accession record and choose Enter Catalog Numbers.  Nothing happens but this message appears behind the scenes.
I don't know if it matters that I created the accession number yyyy-##### after the database was created.  I can open the accession when I choose Create Empty Interaction

Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
java.lang.NullPointerExceptionjava.lang.NullPointerException
	at edu.ku.brc.specify.ui.db.AskForNumbersDlg.createUI(AskForNumbersDlg.java:155)
	at edu.ku.brc.specify.ui.db.AskForNumbersDlg.createUI(AskForNumbersDlg.java:155)	at edu.ku.brc.specify.ui.db.AskForNumbersDlg.createUI(AskForNumbersDlg.java:155)
	at edu.ku.brc.ui.CustomDialog.setVisible(CustomDialog.java:667)
	at edu.ku.brc.ui.CustomDialog.setVisible(CustomDialog.java:667)	at edu.ku.brc.ui.CustomDialog.setVisible(CustomDialog.java:667)
	at edu.ku.brc.af.tasks.BaseTask.askForDataObjRecordSet(BaseTask.java:1313)
	at edu.ku.brc.af.tasks.BaseTask.askForDataObjRecordSet(BaseTask.java:1313)	at edu.ku.brc.af.tasks.BaseTask.askForDataObjRecordSet(BaseTask.java:1313)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:228)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:228)	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:228)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:161)
	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:161)	at edu.ku.brc.specify.tasks.InteractionsProcessor.createOrAdd(InteractionsProcessor.java:161)
	at edu.ku.brc.specify.tasks.InteractionsTask.processInteractionsCommands(InteractionsTask.java:2334)
	at edu.ku.brc.specify.tasks.InteractionsTask.processInteractionsCommands(InteractionsTask.java:2334)	at edu.ku.brc.specify.tasks.InteractionsTask.processInteractionsCommands(InteractionsTask.java:2334)
	at edu.ku.brc.specify.tasks.InteractionsTask.doCommand(InteractionsTask.java:2525)
	at edu.ku.brc.specify.tasks.InteractionsTask.doCommand(InteractionsTask.java:2525)	at edu.ku.brc.specify.tasks.InteractionsTask.doCommand(InteractionsTask.java:2525)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)	at edu.ku.brc.ui.CommandActionWrapper.actionPerformed(CommandActionWrapper.java:82)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by timo11** [comment]
What kind of collection? I don't have any databases where the 'enter catalog numbers' option appears for new accessions.

**Comment by tlammer** [comment]
I created a database in the latest release.  A mammal database.  I get a pop up that asks if I want to enter catalog numbers or Create Empty Interaction
