### ISSUE TITLE
Business Rules error when adding Material Sample to Preparation subform

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#578]
Discovered by Denmark
If you add material sample to Prep as a button, you get a business rule exception upon clicking the button.

java.lang.InternalError: Can't instantiate BusinessRulesIFace [edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRules]java.lang.InternalError: Can't instantiate BusinessRulesIFace [edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRules]
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:298)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:298)	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:298)
	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:350)
	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:350)	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:350)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2574)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2574)	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2574)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:165)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:165)	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:165)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.createUI(ViewBasedDisplayPanel.java:185)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.createUI(ViewBasedDisplayPanel.java:185)	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.createUI(ViewBasedDisplayPanel.java:185)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.<init>(ViewBasedDisplayPanel.java:162)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.<init>(ViewBasedDisplayPanel.java:162)	at edu.ku.brc.af.ui.db.ViewBasedDisplayPanel.<init>(ViewBasedDisplayPanel.java:162)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.<init>(ViewBasedDisplayDialog.java:131)
	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.<init>(ViewBasedDisplayDialog.java:131)	at edu.ku.brc.af.ui.db.ViewBasedDisplayDialog.<init>(ViewBasedDisplayDialog.java:131)
	at edu.ku.brc.af.ui.forms.SubViewBtn$2.<init>(SubViewBtn.java:375)
	at edu.ku.brc.af.ui.forms.SubViewBtn$2.<init>(SubViewBtn.java:375)	at edu.ku.brc.af.ui.forms.SubViewBtn$2.<init>(SubViewBtn.java:375)
	at edu.ku.brc.af.ui.forms.SubViewBtn.showForm(SubViewBtn.java:374)
	at edu.ku.brc.af.ui.forms.SubViewBtn.showForm(SubViewBtn.java:374)	at edu.ku.brc.af.ui.forms.SubViewBtn.showForm(SubViewBtn.java:374)
	at edu.ku.brc.specify.ui.AttachmentSubViewBtn.access$000(AttachmentSubViewBtn.java:42)
	at edu.ku.brc.specify.ui.AttachmentSubViewBtn.access$000(AttachmentSubViewBtn.java:42)	at edu.ku.brc.specify.ui.AttachmentSubViewBtn.access$000(AttachmentSubViewBtn.java:42)
	at edu.ku.brc.specify.ui.AttachmentSubViewBtn$1.actionPerformed(AttachmentSubViewBtn.java:72)
	at edu.ku.brc.specify.ui.AttachmentSubViewBtn$1.actionPerformed(AttachmentSubViewBtn.java:72)	at edu.ku.brc.specify.ui.AttachmentSubViewBtn$1.actionPerformed(AttachmentSubViewBtn.java:72)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at java.awt.Component.processMouseEvent(Component.java:6539)	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Component.processEvent(Component.java:6304)	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Container.processEvent(Container.java:2239)	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.dispatchEvent(Component.java:4711)	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.dispatchEvent(Component.java:4711)	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue.access$500(EventQueue.java:97)	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:709)	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.awt.EventQueue$3.run(EventQueue.java:703)	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:733)	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:731)	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(Native Method)	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRules
Caused by: java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRulesCaused by: java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRules
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName0(Native Method)	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.lang.Class.forName(Class.java:264)	at java.lang.Class.forName(Class.java:264)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)
	... 51 more
	... 51 more	... 51 more
ok
okok

**Comment by tlammer** [comment]
solution seems to be removing the business rules line from the xml.

**Comment by timo11** [comment]
Yes. There are no business rules for MaterialSample.

**Comment by tlammer** [comment]
I removed this line from the MaterialSample view in Common.views and it worked for me
              busrules="edu.ku.brc.specify.datamodel.busrules.MaterialSampleBusRules"
