### ISSUE TITLE
Failed to lazily initialize a collection of role

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#581]
I get a stack trace when saving changes to existing CO. Does not seem to happen for other tables in the same database

Tested in Specify 6.8 with MySQL 5.7, Amazon Corretto 8 and macOS 10.15
Database: `Specify6/Databases/Conversion Databases/Rancho Santa Ana Botanic Garden/2016_04_20_10_49_59.zip/2016_04_20_10_49_59.sql`

```
class_name: edu.ku.brc.af.ui.forms.FormViewObj
comments: 

stack_trace: 
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.ku.brc.specify.datamodel.CollectionObject.dnaSequences, no session or session was closed
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:358)
	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:350)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:343)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.addExtraObjectForProcessing(CollectionObjectBusRules.java:653)
	at edu.ku.brc.specify.datamodel.busrules.AttachmentOwnerBaseBusRules.beforeMerge(AttachmentOwnerBaseBusRules.java:111)
	at edu.ku.brc.specify.datamodel.busrules.CollectionObjectBusRules.beforeMerge(CollectionObjectBusRules.java:591)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2857)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3084)
	at edu.ku.brc.af.ui.forms.FormViewObj.isDataCompleteAndValid(FormViewObj.java:1916)
	at edu.ku.brc.af.ui.forms.MultiView.showView(MultiView.java:796)
	at edu.ku.brc.af.ui.forms.MenuSwitcherPanel$SwitcherAL.actionPerformed(MenuSwitcherPanel.java:264)
	at edu.ku.brc.ui.DropDownButtonStateful.doAdvanceToNextState(DropDownButtonStateful.java:261)
	at edu.ku.brc.ui.DropDownButtonStateful.access$000(DropDownButtonStateful.java:59)
	at edu.ku.brc.ui.DropDownButtonStateful$2.actionPerformed(DropDownButtonStateful.java:187)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Data_Entry
title: 
id: d9a73107-30ba-a3dc-72b7-f1f642eddceb--16f258254c0
os_name: Mac OS X
os_version: 10.15
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2776267344
user_name: specify
ip: 192.168.2.142
app_version: 6.8.00
collection: RSA-POM
discipline: Botany
division: Botanic Garden
institution: Rancho Santa Ana Botanical Garden
Collection_number: 1388506083.88
Discipline_number: 1388506083.8
Division_number: 1388506083.69
Institution_number: 1388506081.68
email: mnazaire@rsabg.org
```

**Comment by maxxxxxdlp** [comment]
Duplicate of #483
