### ISSUE TITLE
Investigate possibly un-supported picklist options.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#610]
The 'Entire Table' and 'Field from Table' picklist types may not be supported. If they are not, they should be removed from the schema config UI.

**Comment by timo11** [comment]
The picklist options DO work. No need to remove them.

"Entire Table" example:

![AccTabEntireTable](https://user-images.githubusercontent.com/2915306/74957660-800da380-53cd-11ea-807f-d1f0117e6285.png)

On the CO form:

`<cell type="field" id="3" name="accession" uitype="combobox" picklist="AccTab" isrequired="false"/>`

Not sure if it is necessary to specify the picklist in the viewdef. It is impossible to assign a new EntireTable picklist to a relationship in the schema config until Specify is restarted, and I did not revise the form after updating the schema config.

**Comment by maxxxxxdlp** [comment]
I had this happen once:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: setSelectedIndex: 1 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:620)
	at edu.ku.brc.specify.datamodel.busrules.AgentBusRules.afterFillForm(AgentBusRules.java:441)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:5400)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataIntoUI(FormViewObj.java:4943)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4776)
	at edu.ku.brc.af.ui.forms.FormViewObj.setDataObj(FormViewObj.java:4374)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1212)
	at edu.ku.brc.af.ui.forms.MultiView.setData(MultiView.java:1171)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:468)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:290)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1826)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2214)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.core.NavBoxAction.actionPerformed(NavBoxAction.java:179)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
but mostly seems to work fine
