### ISSUE TITLE
Exception when saving `DNA Sequence`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#618]
Exception when saving `DNA Sequence`
Seems to be caused by the length of the value in some field. If this is the case, the user should not be able to enter the data that raises an error

![Screenshot from 2020-02-25 09-00-53](https://user-images.githubusercontent.com/40512816/75259262-5b3e7500-57ad-11ea-8a3e-0d75049d7afb.png)

```
class_name: edu.ku.brc.specify.ui.db.PickListDBAdapter
comments: 

stack_trace: 
org.hibernate.exception.DataException: could not insert: [edu.ku.brc.specify.datamodel.PickListItem]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:77)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:40)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2631)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.engine.CascadingAction$1.cascade(CascadingAction.java:218)
	at org.hibernate.engine.Cascade.cascadeToOne(Cascade.java:268)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:216)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascadeCollectionElements(Cascade.java:296)
	at org.hibernate.engine.Cascade.cascadeCollection(Cascade.java:242)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:219)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:130)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:97)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.cascadeOnUpdate(DefaultSaveOrUpdateEventListener.java:357)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:329)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:223)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:89)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:495)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.saveOrUpdate(HibernateDataProviderSession.java:549)
	at edu.ku.brc.specify.ui.db.PickListDBAdapter.save(PickListDBAdapter.java:265)
	at edu.ku.brc.specify.ui.db.PickListDBAdapter.addItem(PickListDBAdapter.java:236)
	at edu.ku.brc.af.ui.forms.validation.ValComboBox.getValue(ValComboBox.java:975)
	at edu.ku.brc.af.ui.forms.FormViewObj.getValueFromComponent(FormViewObj.java:5661)
	at edu.ku.brc.af.ui.forms.FormViewObj.getDataFromUIComp(FormViewObj.java:5732)
	at edu.ku.brc.af.ui.forms.FormViewObj.getDataFromUI(FormViewObj.java:5575)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2798)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3089)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:883)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'Title' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:73)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:33)
	... 78 more

task_name: Data_Entry
title: 
id: 767063a4-c0ee-ec40-ebcd-acca3a334ef5--17078ffe080
os_name: Linux
os_version: 5.0.0-37-generic
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2564050592
user_name: m001p596
ip: 127.0.0.1
app_version: 6.8.00
collection: ~!@#$%^&*()_+_)(*&^%$#!$#%#%$&&(@#$%@#$%@#$%@#$%@#
discipline: ~!@#$%^&*()_+_)(*&^%$#!$#%#%$&&(~!@#$%^&*()_+_)(*&^%$#!$#%#%$&&(
division: a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@#$%@#%^$#@%^$#%^#$%^@$%$@#$%@#$%@%^@$%^#^&$%^&%*%^&*#^@$%^#$%@#
institution: a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@a!@#$%^&*()_++_)(*&^%$#@!@#$%^&*()_+^%$#!~@%$^&*(*&_*)*^%^#%@##@
Collection_number: 1582583196.6375
Discipline_number: 1582583196.3314
Division_number: 1582583195.9978
Institution_number: 1582583195.0849
email: !@#$%^&*()(*&^%$#@!!@#$%^&*()(*&^%$#@!{}{}":":?>?>
```

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/FabioZumbi12/RedProtect, https://github.com/apache/skywalking and https://github.com/EsupPortail/esup-smsu-api. Perhaps we can refer to [this issue](https://github.com/FabioZumbi12/RedProtect/issues/670), [this one](https://github.com/apache/skywalking/issues/5236) and [this](https://github.com/EsupPortail/esup-smsu-api/issues/10) to find more context about the bug. 
Or maybe this can help us find the faulty lines and we can also refer to the [fix](https://github.com/FabioZumbi12/RedProtect/commit/ef0a1171a02a90797fb08ad926f24be52e6b99ca) or https://github.com/apache/skywalking/pull/5238 or https://github.com/EsupPortail/esup-smsu-api/commit/32046378f49f6edf876e7d4c60b785b4e927e208 for the bug?
