### ISSUE TITLE
Exception when opening the `Taxon` tree

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#629]
Exception when opening the `Taxon` tree

<img width="1440" alt="Screen Shot 2020-02-27 at 10 25 44 AM" src="https://user-images.githubusercontent.com/40512816/75463496-86f76180-594b-11ea-9efe-a86a240852f0.png">

<img width="582" alt="Screen Shot 2020-02-27 at 10 26 45 AM" src="https://user-images.githubusercontent.com/40512816/75463635-b1491f00-594b-11ea-8b7c-41b9f931bf58.png">

See also #555

```
class_name: edu.ku.brc.specify.treeutils.HibernateTreeDataServiceImpl
comments: 

stack_trace: 
org.hibernate.exception.SQLGrammarException: could not initialize a collection: [edu.ku.brc.specify.datamodel.TaxonTreeDefItem.treeEntries#1]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:67)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:2001)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:60)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:344)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.iterator(PersistentSet.java:163)
	at edu.ku.brc.specify.treeutils.HibernateTreeDataServiceImpl.getRootNode(HibernateTreeDataServiceImpl.java:315)
	at edu.ku.brc.specify.ui.treetables.TreeTableViewer.initTreeLists(TreeTableViewer.java:360)
	at edu.ku.brc.specify.ui.treetables.TreeTableViewer$1.construct(TreeTableViewer.java:299)
	at edu.ku.brc.helpers.SwingWorker$2.run(SwingWorker.java:133)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'treeentrie0_.TaxonAttributeID' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
	at org.hibernate.loader.Loader.doQuery(Loader.java:674)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	... 12 more

task_name: TaxonTree
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--170838878a0
os_name: Mac OS X
os_version: 10.15.4
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2491995688
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1582586189.6417
Discipline_number: 1582586189.3157
Division_number: 1582586189.0037
Institution_number: 1582586187.6878
email: 1
```

**Comment by timo11** [comment]
Probably the db schema needs to be updated? Set the always update local pref, whatever it is, to true, or set the value of spversion.schemaversion back to '2.6'.

**Comment by maxxxxxdlp** [comment]
That fixed the problem. No idea what caused it to appear in the first place

**Comment by timo11** [comment]
The taxonattribute table hadn't been added to the db.
