### ISSUE TITLE
Install4J exception during packaging.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify6#63]
The exception below occurs during packaging. It doesn't cause the packaging to fail but adds noise to log. It seems that the `CheckForUpdateAction.setConnectTimeout` method was removed or otherwise doesn't exist in the version of Install4J we are currently using.

```     [exec] Serialization error for bean class com.install4j.runtime.beans.actions.update.CheckForUpdateAction:
     [exec] java.lang.NoSuchMethodException: <unbound>=CheckForUpdateAction.setConnectTimeout("30000");
     [exec] 	at java.beans.Statement.invokeInternal(Statement.java:313)
     [exec] 	at java.beans.Statement.access$000(Statement.java:58)
     [exec] 	at java.beans.Statement$2.run(Statement.java:185)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.beans.Statement.invoke(Statement.java:182)
     [exec] 	at java.beans.Expression.getValue(Expression.java:153)
     [exec] 	at com.sun.beans.decoder.ObjectElementHandler.getValueObject(ObjectElementHandler.java:166)
     [exec] 	at com.sun.beans.decoder.NewElementHandler.getValueObject(NewElementHandler.java:123)
     [exec] 	at com.sun.beans.decoder.ElementHandler.endElement(ElementHandler.java:169)
     [exec] 	at com.sun.beans.decoder.DocumentHandler.endElement(DocumentHandler.java:318)
     [exec] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
     [exec] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
     [exec] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
     [exec] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
     [exec] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
     [exec] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
     [exec] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
     [exec] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [exec] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
     [exec] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
     [exec] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
     [exec] 	at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:375)
     [exec] 	at com.sun.beans.decoder.DocumentHandler$1.run(DocumentHandler.java:372)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
     [exec] 	at com.sun.beans.decoder.DocumentHandler.parse(DocumentHandler.java:372)
     [exec] 	at java.beans.XMLDecoder$1.run(XMLDecoder.java:201)
     [exec] 	at java.beans.XMLDecoder$1.run(XMLDecoder.java:199)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.beans.XMLDecoder.parsingComplete(XMLDecoder.java:199)
     [exec] 	at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
     [exec] 	at com.install4j.config.a.e.z(ejt:237)
     [exec] 	at com.install4j.config.a.e.w(ejt:190)
     [exec] 	at com.install4j.config.a.a.F(ejt:128)
     [exec] 	at com.install4j.config.a.a.d(ejt:106)
     [exec] 	at com.a.b.b.p.b(ejt:49)
     [exec] 	at com.install4j.config.a.ah.e(ejt:236)
     [exec] 	at com.install4j.config.a.ah.d(ejt:213)
     [exec] 	at com.a.b.b.p.b(ejt:49)
     [exec] 	at com.install4j.config.a.ab.b(ejt:370)
     [exec] 	at com.install4j.config.a.ab.d(ejt:304)
     [exec] 	at com.a.b.b.p.b(ejt:49)
     [exec] 	at com.install4j.config.p.d(ejt:270)
     [exec] 	at com.install4j.config.p.a(ejt:28)
     [exec] 	at com.install4j.config.q.run(ejt:259)
     [exec] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
     [exec] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
     [exec] 	at java.awt.EventQueue.access$300(EventQueue.java:103)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:706)
     [exec] 	at java.awt.EventQueue$3.run(EventQueue.java:704)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
     [exec] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
     [exec] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
     [exec] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
     [exec] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
     [exec] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by timo11** [comment]
That parameter was supposed to have fixed a problem with Specify hanging for 5 - 10 minutes when our update server was down.

Maybe it never actually worked. Or maybe we updated install4j? If so hopefully the default behavior will handle dead servers w/o less of a wait.

**Comment by benanhalt** [comment]
Yeah, I tried looking to see if it was an option in older versions of Install4J, but it is really hard to find out. I even resorted to grepping the contents of `i4jruntime.jar` in various versions. It seems like maybe it was added in later versions? Perhaps it was tested with an evaluation copy of a newer version. Unfortunately our license is only good for Install4J v5. At any rate, the option was also being rejected on the build machine for previous versions of Specify. I remember seeing this exception pile up on the console.

I'll try checking to see how long it hangs when it can't connect to the server.

**Comment by benanhalt** [comment]
I adjusted the update URLs in a copy of Specify on my machine to `localhost:8888` and arranged a blocked http server, `python -m SimpleHTTPServer 8888` put to sleep with `^Z`. Specify then pauses for 12s at login while waiting on the server before proceeding to start up normally with no error. Manually checking for updates through the *Help* menu results in Specify hanging for ~10s and then displaying a dialog that checking for updates failed. The failing manual update check also produces a SocketTimeoutException in the log.
