### ISSUE TITLE
Unable to add ConservEvent attachments on CO form.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#631]
Reported by Niels K. of MEL

If I create a CO record and save a conservator description record with a conservation event associated, I have no issues.  If I do the same thing but I attach something to conservation event, I get an error when saving the CO record (same one as he sent below).
If I do the same thing but start from Conservator desc instead of CO, i have no issues.

stack_trace:

org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.Attachment.tableID

                at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)

                at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)

                at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)

                at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)

                at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)

                at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)

                at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:687)

                at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:669)

**Comment by timo11** [comment]
This is caused by the same problem as #324.

**Comment by yvonneekanim** [comment]
I'm able to add CE attachments when CD is a button or embedded in CO form
