### ISSUE TITLE
Creating a print report fails when timestamp fields selected

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#638]
Reported by @timo11 

Creating a print report for the `Sp Audit Log` table fails
<img width="600" alt="Screen Shot 2020-03-03 at 11 51 53 AM" src="https://user-images.githubusercontent.com/40512816/75804309-619c9600-5d45-11ea-93d7-97c390eda209.png">

**Comment by maxxxxxdlp** [comment]
Here is the exception:
```
net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression : 
	Source text : $F{Timestamp Created}
	at net.sf.jasperreports.engine.fill.JREvaluator.evaluate(JREvaluator.java:263)
	at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:611)
	at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:579)
	at net.sf.jasperreports.engine.fill.JRFillElement.evaluateExpression(JRFillElement.java:1016)
	at net.sf.jasperreports.engine.fill.JRFillTextField.evaluateText(JRFillTextField.java:504)
	at net.sf.jasperreports.engine.fill.JRFillTextField.evaluate(JRFillTextField.java:488)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:259)
	at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:456)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2067)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:788)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:298)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:152)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:963)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:892)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:114)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:668)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:984)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:284)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:236)
	at edu.ku.brc.specify.tasks.ReportsBaseTask$1.doInBackground(ReportsBaseTask.java:1074)
	at edu.ku.brc.specify.tasks.ReportsBaseTask$1.doInBackground(ReportsBaseTask.java:1057)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.sql.Timestamp
	at DJR_7625_1583786369777_551287.evaluate(DJR_7625_1583786369777_551287:390)
	at net.sf.jasperreports.engine.fill.JREvaluator.evaluate(JREvaluator.java:250)
	... 26 more

```

**Comment by maxxxxxdlp** [comment]
Happens when either one of these fields is selected in a query

<img width="489" alt="Screen Shot 2020-03-09 at 3 42 03 PM" src="https://user-images.githubusercontent.com/40512816/76255644-89e03500-621c-11ea-850c-443c26ef66e5.png">
