### ISSUE TITLE
prep guid fix doesn't work for mysql 5.7.6 and up

### ISSUE THREAD

**Issue by timo11** [specify/specify6#64]
Prep guid fix causes this on mysql 5.7.6 and up:

stack_trace: 
java.sql.SQLException: You can't specify target table 'pup' for update in FROM clause
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.update(BasicSQLUtils.java:1082)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.update(BasicSQLUtils.java:1066)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.fixDupPrepGuids(SpecifySchemaUpdateService.java:2544)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.manuallyFixDB(SpecifySchemaUpdateService.java:2500)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.updateSchema(SpecifySchemaUpdateService.java:495)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.doLoginContinuing2(DatabaseLoginPanel.java:1387)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17$2.exited(DatabaseLoginPanel.java:1357)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.exited(Unknown Source)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.run(Unknown Source)

This: https://duckduckgo.com/?q=You+can%27t+specify+target+table+for+update+in+FROM+clause+in+mysql5.7+but+not+mariadb+10.2&t=ffnt&ia=qa&iax=qa

revealed this:

 ... but watch out for the query optimiser

However, beware that from MySQL 5.7.6 and onward, the optimiser may optimise out the subquery, and still give you the error. Luckily, the optimizer_switch variable can be used to switch off this behaviour; although I couldn't recommend doing this as anything more than a short term fix, or for small one-off tasks.

SET optimizer_switch = 'derived_merge=off';

Thanks to Peter V. Mørch for this advice in the comments.

Example technique was from Baron Schwartz, originally published at Nabble, paraphrased and extended here.

**Comment by garrettgirard** [comment]
This appears to finally be working. Tested in KU Fish which had this issue.
