### ISSUE TITLE
Add SpAuditLog permissions to security config tool. 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#653]

**Comment by maxxxxxdlp** [comment]
I removed the permissions for all tables (except for Auditing) for the user

<img width="1440" alt="Screen Shot 2020-03-09 at 8 46 31 AM" src="https://user-images.githubusercontent.com/40512816/76218657-9ba4e680-61e2-11ea-931c-bf8fe14d5ecb.png">

Yet I am still able to query all of the tables

<img width="1440" alt="Screen Shot 2020-03-09 at 8 46 40 AM" src="https://user-images.githubusercontent.com/40512816/76218664-9e074080-61e2-11ea-9969-8ee27c2a300b.png">

When I tried to remove the Auditing table permissions (with the user being not logged in), I received the following exception:
```
class_name: edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane
comments: 

stack_trace: 
edu.ku.brc.dbsupport.StaleObjectException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpecifyUser#2]
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:224)
	at edu.ku.brc.specify.tasks.subpane.security.AdminInfoSubPanelWrapper.savePermissionData(AdminInfoSubPanelWrapper.java:394)
	at edu.ku.brc.specify.tasks.subpane.security.SecurityAdminPane.doSave(SecurityAdminPane.java:1197)
	at edu.ku.brc.specify.tasks.subpane.security.EditorPanel$1.actionPerformed(EditorPanel.java:66)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [edu.ku.brc.specify.datamodel.SpecifyUser#2]
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:261)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:120)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	... 39 more

task_name: SecurityAdmin
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--170b2195ea0
os_name: Mac OS X
os_version: 10.15.4
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 317767568
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1583761039.4796
Discipline_number: 1583761039.2317
Division_number: 1583761039.0252
Institution_number: 1583761037.6562
email: 1
```

**Comment by maxxxxxdlp** [comment]
Works well besides that one exception
All the tests I done are outlined below

---

User type: Guest
Locality: all permissions
SpAuditLog: view
SpAuditLogFields: view
<img width="1440" alt="Screen Shot 2020-03-09 at 9 32 15 AM" src="https://user-images.githubusercontent.com/40512816/76222852-2a1c6680-61e9-11ea-9fb2-b5012456a556.png">
<img width="1440" alt="Screen Shot 2020-03-09 at 9 32 23 AM" src="https://user-images.githubusercontent.com/40512816/76222853-2a1c6680-61e9-11ea-9c54-b5a41d9e8ccf.png">

---

User type: Guest
Locality: all permissions
SpAuditLog: view
SpAuditLogFields: no permissions
<img width="1440" alt="Screen Shot 2020-03-09 at 9 34 12 AM" src="https://user-images.githubusercontent.com/40512816/76222855-2ab4fd00-61e9-11ea-97e7-fb96e30752e5.png">

---

User type: Guest
Locality: all permissions
SpAuditLog: view
SpAuditLogFields: view

Changes still were logged and viewable only by the admin
<img width="1440" alt="Screen Shot 2020-03-09 at 9 40 21 AM" src="https://user-images.githubusercontent.com/40512816/76225086-00177400-61ea-11ea-87f5-5773e67a6aa4.png">

---
