### ISSUE TITLE
Null pointer exception when adding pcr persons and extractors to form

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#675]
I'm getting the following error:
java.lang.NullPointerException
	at edu.ku.brc.specify.datamodel.busrules.DNASequenceBusRules.initialize(DNASequenceBusRules.java:72)
	at edu.ku.brc.af.ui.forms.FormViewObj.setFormComp(FormViewObj.java:1574)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2630)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:252)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2867)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:977)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:933)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:280)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:146)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:426)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:290)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1826)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2214)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.core.NavBoxAction.actionPerformed(NavBoxAction.java:179)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by timo11** [comment]
This seems to be happening because the IllustrativeBarCodeUI plugin (id="8") has been removed from the form but its dependent (according to the busrules) control (id="4") is still on the form. I will add a null pointer check to fix this specific issue, but other things could go wrong. It might be better to just put the IllustrativeBarCodeUI field back on the form if possible. (Also the busrules require these two fields have ids "4" and "8", and that no other fields on the form ever get those ids.).

**Comment by timo11** [comment]
@yvonneekanim  can you put the db on specify6? Or at least attach or email me the viewdef for DNASequence? "8" has been taken off the default form, but the exception actually indicates '4' is missing from the form your instance is using.

**Comment by yvonneekanim** [comment]
@timo11 here is the viewdef for DNASequence. I add those fields to the form from the commented out section

        <viewdef 
            name="DNASequence"
            type="form"
            class="edu.ku.brc.specify.datamodel.DNASequence" 
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" 
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[DNA Sequence Form]]></desc>
            <enableRules/>
        
            <columnDef>100px,2px,86px,2px,115px,5px,103px,2px,190px,5px,110px,2px,130px,0px,15px,p:g</columnDef>
            <columnDef os="lnx">115px,2px,76px,2px,123px,2px,140px,2px,163px,5px,135px,2px,150px,0px,15px,p:g</columnDef>
            <columnDef os="mac">130px,2px,96px,2px,133px,2px,160px,2px,173px,5px,155px,2px,170px,0px,15px,p:g</columnDef>
            <columnDef os="exp">p,2px,max(100px;p),2px,p:g(2),5px,p:g,2px,p:g,5px:g,p,2px,p:g,0px,15px,p:g</columnDef>
            <rowDef auto="true" cell="p" sep="2px"/>
            
            <rows>
                <row>
                    <cell type="label" labelfor="gan"/>
                    <cell type="field" id="gan" name="genbankAccessionNumber" uitype="text" colspan="3"/>
                    <cell type="label" labelfor="11"/>
                    <cell type="field" id="11" name="boldBarcodeId" uitype="text"/>
                    <cell type="label" labelfor="bsid"/>
                    <cell type="field" id="bsid" name="boldSampleID" uitype="text"/>
                </row>
                <row>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="moleculeType" uitype="combobox" colspan="3"/>
                    <cell type="label" labelfor="tm"/>
                    <cell type="field" id="tm" name="targetMarker" uitype="text"/>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="boldLastUpdateDate" uitype="formattedtext" uifieldformatter="Date" default="Today"/>
                </row>
                <row>
                    <cell type="label" labelfor="sd"/>
                    <cell type="field" id="sd" uitype="plugin" name="this" initialize="name=PartialDateUI;df=sequenceDate;tp=sequenceDatePrecision" uifieldformatter="Date" colspan="3"/>
                    <cell type="label" labelfor="7"/>
                    <cell type="field" id="7" name="collectionObject" uitype="querycbx" initialize="name=CollectionObject;editbtn=false;newbtn=false"/>
                    <cell type="subview" viewname="DNASequenceRun" id="21" name="dnaSequencingRuns" initialize="btn=true;align=right"/>
                    <cell type="subview" id="attachments" viewname="ObjectAttachment" name="attachments" initialize="btn=true;icon=DNASequenceAttachment;align=right"/>
                </row>
                <row>
                    <cell type="subview" viewname="PcrPersons" id="12" name="pcrPersons" colspan="13" rows="3"/>
                </row>
                <row>
                    <cell type="subview" viewname="Extractors" id="exts" name="extractors" colspan="13" rows="3"/>
                    <cell type="label" labelfor="ed"/>
                    <cell type="field" id="ed" uitype="plugin" name="this" initialize="name=PartialDateUI;df=extractionDate;tp=extractionDatePrecision" uifieldformatter="Date"/>
                </row>
                <row>
                    <cell type="separator" label="Nucleotide Sequence" colspan="15"/>
                </row>
                <row>
                    <cell type="panel" id="16" name="outerPanel" coldef="p,2px,p:g" rowdef="p,2px,p,2px,p,2px,p,2px,p,2px,p,2px" colspan="3">
                      <rows>
	                      <row>
	                          <cell type="label" label="Total Residues:" initialize="align=right"/>
	                          <cell type="field" id="residues" name="totalResidues" uitype="text" readonly="true"/>
	                      </row>
	                      <row>
	                          <cell type="label" label="Comp A:" initialize="align=right;fg=0,190,0"/>
	                          <cell type="field" id="compA" name="compA" uitype="text" readonly="true"/>
	                      </row>
	                      <row>
	                          <cell type="label" label="Comp G:" initialize="align=right;fg=200,70,0"/>
	                          <cell type="field" id="compG" name="compG" uitype="text" readonly="true"/>
	                      </row>
	                      <row>
	                          <cell type="label" label="Comp C:" initialize="align=right;fg=0,0,190"/>
	                          <cell type="field" id="compC" name="compC" uitype="text" readonly="true"/>
	                      </row>
	                      <row>
	                          <cell type="label" label="Comp T:" initialize="align=right;fg=190,0,0"/>
	                          <cell type="field" id="compT" name="compT" uitype="text" readonly="true"/>
	                      </row>
	                      <row>
	                          <cell type="label" label="Ambiguous:" initialize="align=right"/>
	                          <cell type="field" id="ambiguous" name="ambiguousResidues" uitype="text" readonly="true"/>
	                      </row>
	                  </rows>
	              </cell>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="geneSequence" uitype="textareabrief" colspan="7" rows="10"/>
	              </row>
	              
            </rows>
        </viewdef>

**Comment by timo11** [comment]
I added the rows below to the form and had no problems. 

The business rules also seem fine with the missing BarCodeUI plugin, as long as the control with id="4" is geneSequence.
 
When does the error happen exactly? Does it maybe happen even extractors and pcrpersons aren't there?

 <row>
                <cell type="subview" viewname="PcrPersons" id="12" name="pcrPersons" colspan="13" rows="3"/>
</row>
 <row>
                <cell type="subview" viewname="Extractors" id="exts" name="extractors" colspan="13" rows="3"/>
  </row>
`

**Comment by yvonneekanim** [comment]
It only happens when these rows are added:
                <row>
                    <cell type="subview" viewname="Extractors" id="exts" name="extractors" colspan="13" rows="3"/>
                    <cell type="label" labelfor="ed"/>
                    <cell type="field" id="ed" uitype="plugin" name="this" initialize="name=PartialDateUI;df=extractionDate;tp=extractionDatePrecision" uifieldformatter="Date"/>
                </row>

**Comment by timo11** [comment]
When when I add the partial date field I get error message popups about an invalid col index when the form displays, and the control does not display. (And I still don't get the BusRule exception) When I change the colspan for PcrPersons to "12". Everything works. 
Maybe the BusRule error is another consequence of the invalid col index. You must be using a mac. If only there were a corona virus for macs. Now that's a cull I could get behind.

**Comment by timo11** [comment]
Also, I think the extractiondate field should be on a different row than the pcrpersons subform.
