### ISSUE TITLE
Error when logging into Specify

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#683]
I'm using a release from 3 hours ago

class_name: edu.ku.brc.specify.config.SpecifyAppContextMgr
comments: 

stack_trace: 
org.hibernate.exception.SQLGrammarException: could not initialize a collection: [edu.ku.brc.specify.datamodel.SpecifyUser.agents#1]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:67)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:2001)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:60)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:344)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:109)
	at org.hibernate.collection.PersistentSet.size(PersistentSet.java:139)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1301)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1222)
	at edu.ku.brc.specify.Specify.restartApp(Specify.java:2518)
	at edu.ku.brc.specify.Specify.loggedIn(Specify.java:2967)
	at edu.ku.brc.ui.UIHelper$1DBListener.loggedIn(UIHelper.java:1859)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel.loginOK(DatabaseLoginPanel.java:1066)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.finished(DatabaseLoginPanel.java:1455)
	at edu.ku.brc.helpers.SwingWorker$1.run(SwingWorker.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'agents0_.Date1' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
	at org.hibernate.loader.Loader.doQuery(Loader.java:674)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	... 30 more

task_name: 
title: 
id: f976b698-1604-8199-ff51-b3987e22e306--170f8d4caa0
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_202
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 92123432
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: No Institution
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: No Institution Number

**Comment by timo11** [comment]
The schema needs to be updated. Set spversion.schemaversion = '2.6'

**Comment by yvonneekanim** [comment]
These are databases I have previously updated to 6.8. It happens with every database on my pc including those that are 6.7.04 that should update when I login to 6.8

**Comment by timo11** [comment]
databases previously updated to 6.8.00 need to be update again by setting the schemaversion to '2.6'.

The 6.7.04 dbs did not update?

**Comment by maxxxxxdlp** [comment]
Works on my Windows VM with a fresh biology database
Works on my MacBook with a fresh biology database

So this is not a Specify issue

**Comment by yvonneekanim** [comment]
It has been resolved. Thanks
