### ISSUE TITLE
`Can't find bundle for base name resources` when opening DataExporter

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#685]
This error happens in the latest backup of KU Fish updated to the latest Specify 6.8

The error appears when the user opens DataExporter
After closing it, the login screen appears and the application seems to work normally from that point on

This error is not critical because I did not find it for any other database
I don't think that it can be fixed by a schema update, because this database has had its schema update 5 minutes ago

```
java.util.MissingResourceException: Can't find bundle for base name resources, locale 
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at edu.ku.brc.specify.tools.export.ExportPanel.adjustLocaleFromPrefs(ExportPanel.java:2015)
	at edu.ku.brc.specify.tools.export.ExportPanel.startupContinuing(ExportPanel.java:1831)
	at edu.ku.brc.specify.tools.export.ExportPanel.access$300(ExportPanel.java:79)
	at edu.ku.brc.specify.tools.export.ExportPanel$21.run(ExportPanel.java:1818)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by timo11** [comment]
The error seems to be related to the local locale prefs, and completely database-independent so I don't know why it would only happen for KU fish.

**Comment by maxxxxxdlp** [comment]
You were right. It happens for all other databases too

Besides that error, I also got this when logging in into a different database
```
class_name: edu.ku.brc.specify.config.SpecifyAppContextMgr
comments: 

stack_trace: 
org.hibernate.exception.SQLGrammarException: could not initialize a collection: [edu.ku.brc.specify.datamodel.SpecifyUser.agents#1]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:67)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:2001)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:60)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:344)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:109)
	at org.hibernate.collection.PersistentSet.size(PersistentSet.java:139)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1301)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1222)
	at edu.ku.brc.specify.tools.export.SchemaExportLauncher.loggedIn(SchemaExportLauncher.java:71)
	at edu.ku.brc.ui.UIHelper$1DBListener.loggedIn(UIHelper.java:1859)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel.loginOK(DatabaseLoginPanel.java:1066)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.finished(DatabaseLoginPanel.java:1455)
	at edu.ku.brc.helpers.SwingWorker$1.run(SwingWorker.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'agents0_.Date1' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
	at org.hibernate.loader.Loader.doQuery(Loader.java:674)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	... 29 more

task_name: 
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--170f8d40750
os_name: Mac OS X
os_version: 10.15.4
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 1908932608
used_memory: 1355123456
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: No Institution
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: No Institution Number

```

Here are my local prefs:
<img width="1440" alt="Screen Shot 2020-03-20 at 3 27 08 PM" src="https://user-images.githubusercontent.com/40512816/77203925-a9e6e280-6abf-11ea-8f4a-822c2da67849.png">
<img width="1440" alt="Screen Shot 2020-03-20 at 3 27 14 PM" src="https://user-images.githubusercontent.com/40512816/77203927-aa7f7900-6abf-11ea-9d18-ce3ccd964f81.png">
<img width="1430" alt="Screen Shot 2020-03-20 at 3 27 50 PM" src="https://user-images.githubusercontent.com/40512816/77203928-aa7f7900-6abf-11ea-8cb3-0890ada6ca9f.png">

**Comment by maxxxxxdlp** [comment]
First one was fixed
I forgot to set a value for `locale.lang` in `user.preferences`
