### ISSUE TITLE
Not-null property references a null or transient value in WorkBench

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#716]
This exception happens in the background & foreground when the uses presses the `Upload` button in the WorkBench

```
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.AccessionAgent.role
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6510)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRowOrNot(UploadTable.java:6097)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.writeRow(UploadTable.java:5859)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.writeRow(Uploader.java:5582)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.uploadRow(Uploader.java:5546)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$15.doInBackground(Uploader.java:4529)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.AccessionAgent.role
	at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:495)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.saveOrUpdate(HibernateDataProviderSession.java:549)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.doWrite(UploadTable.java:6478)
	... 11 more
```

![Screenshot from 2020-04-01 10-10-41](https://user-images.githubusercontent.com/40512816/78166039-112a5e00-7401-11ea-9871-5d40a03e85e8.png)

Here is the Data Set:
[1.zip](https://github.com/specify/specify6/files/4416618/1.zip)

![Screenshot from 2020-04-01 10-08-32](https://user-images.githubusercontent.com/40512816/78165895-d88a8480-7400-11ea-9160-d4909feaa90a.png)

**Comment by timo11** [comment]
This is happening because the requirement for Role is only enforced for the first Authority.

**Comment by timo11** [comment]
PrepType is enforced for all preps.

**Comment by timo11** [comment]
This is the antibug of bi-bugs.home.ku.edu/bugs/show_bug.cgi?id=9012 which turned to the dark side on 12/12/12, before its incomplete fix could be tested.

**Comment by timo11** [comment]
Unable to duplicate.

**Comment by maxxxxxdlp** [comment]
The `highlight invalid cells` bug does not happen after creating a new data set

All `Authority Role#` fields still have a blue background regardless of which cells are selected. Is it a bug or a "feature"? 👍 
<img width="1440" alt="Screen Shot 2020-04-03 at 3 09 27 PM" src="https://user-images.githubusercontent.com/40512816/78400922-32d04480-75bd-11ea-9e2a-d7b4f6c05d5f.png">

**Comment by maxxxxxdlp** [comment]
Now I get the following error:

<img width="1440" alt="Screen Shot 2020-04-03 at 3 13 15 PM" src="https://user-images.githubusercontent.com/40512816/78401133-a5d9bb00-75bd-11ea-810e-2f7a381180a8.png">


```
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: java.util.ConcurrentModificationException
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: java.util.ConcurrentModificationExceptionedu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: java.util.ConcurrentModificationException
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5130)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5130)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5130)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$15.doInBackground(Uploader.java:4539)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$15.doInBackground(Uploader.java:4539)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader$15.doInBackground(Uploader.java:4539)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.lang.Thread.run(Thread.java:748)	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
Caused by: java.util.ConcurrentModificationExceptionCaused by: java.util.ConcurrentModificationException
	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1703)
	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1703)	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1703)
	at java.util.TreeMap$NavigableSubMap$SubMapKeyIterator.next(TreeMap.java:1780)
	at java.util.TreeMap$NavigableSubMap$SubMapKeyIterator.next(TreeMap.java:1780)	at java.util.TreeMap$NavigableSubMap$SubMapKeyIterator.next(TreeMap.java:1780)
	at java.util.AbstractSet.removeAll(AbstractSet.java:174)
	at java.util.AbstractSet.removeAll(AbstractSet.java:174)	at java.util.AbstractSet.removeAll(AbstractSet.java:174)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.abortRow(UploadTable.java:6627)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.abortRow(UploadTable.java:6627)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploadTable.abortRow(UploadTable.java:6627)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5122)
	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5122)	at edu.ku.brc.specify.tasks.subpane.wb.wbuploader.Uploader.abortRow(Uploader.java:5122)
	... 7 more
	... 7 more	... 7 more
```

**Comment by timo11** [comment]
Is there a mouse over hint for the Role cells?

**Comment by maxxxxxdlp** [comment]
Does not seem so

**Comment by timo11** [comment]
The last error might be happening because you are adding the same agent and role more than once.
Still unable to make dark blue cells for myself.

**Comment by timo11** [comment]
If the row is selected and the cells don't have any highlights they will display in the row selected color, right? I don't see the problem.

**Comment by timo11** [comment]
@maxxxxxdlp  please make a new bug for the highlighted agent cells and the broken highlight invalid cells if it can be duplicated.

**Comment by maxxxxxdlp** [comment]
Here is the video of me replicating this bug:
https://youtu.be/GKYejmGdQLQ

**Comment by timo11** [comment]
Still can't duplicate. Put the blue cell stuff in another bug please.
