### ISSUE TITLE
Add getResolved, getResolvedQuantity fields to Loan

### ISSUE THREAD

**Issue by timo11** [specify/specify6#724]

**Comment by timo11** [comment]
the new fields are 'resolvedItems' and 'resolvedQuantities'.

**Comment by maxxxxxdlp** [comment]
@timo11 is there a way to test it? Since #718 is confirmed fixed is this too?

**Comment by timo11** [comment]
They need and should be put on a loan form to be tested. I'm not sure if they need to be added to the default loan form.

**Comment by maxxxxxdlp** [comment]
I probably did something wrong, but I get two exceptions when opening the `Loan` form after editing the `common.views.xml` file

<img width="1069" alt="Screen Shot 2020-04-09 at 2 36 07 PM" src="https://user-images.githubusercontent.com/40512816/78934082-f0e94780-7a6f-11ea-8a05-a3b310647104.png">

![Screen Shot 2020-04-09 at 2 39 17 PM](https://user-images.githubusercontent.com/40512816/78934097-f9da1900-7a6f-11ea-879a-89be5a815492.png)
I changed the `name` attribute value for two fields

<img width="1017" alt="Screen Shot 2020-04-09 at 2 39 30 PM" src="https://user-images.githubusercontent.com/40512816/78934074-ecbd2a00-7a6f-11ea-8f80-53465233ffcf.png">

**Comment by timo11** [comment]
It works for me, and it looks like the form is right. Are you running from a build? If not maybe loan.java is not up to date?

**Comment by maxxxxxdlp** [comment]
Reinstalled specify
Recreated database
Still get the exception I outlined before. I forgot to mention that I am getting it twice (probably because I modified two fields)

Besides that, I get a new exception (only if I have specified a CO number):
```
class_name: edu.ku.brc.specify.conversion.BasicSQLUtils
comments: 

stack_trace: 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'specify.p.PreparationID'; this is incompatible with sql_mode=only_full_group_by
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.query(BasicSQLUtils.java:781)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.query(BasicSQLUtils.java:725)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.getAvailableCounts(InteractionsProcessor.java:551)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.collect(InteractionsProcessor.java:566)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.doInBackground(InteractionsProcessor.java:607)
	at edu.ku.brc.specify.tasks.InteractionsProcessor$PrepLoaderSQL.doInBackground(InteractionsProcessor.java:439)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: Interactions
title: 
id: b8c3a206-95cb-8cbc-cc44-c3e2046adca3--17165182770
os_name: Mac OS X
os_version: 10.15.4
java_version: 1.8.0_232
java_vendor: Amazon.com Inc.
max_memory: 3817865216
used_memory: 2954199080
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00
collection: 1
discipline: Botany
division: 1
institution: 1
Collection_number: 1586542010.5053
Discipline_number: 1586542010.2621
Division_number: 1586542009.9463
Institution_number: 1586542008.4955
email: 1
```

**Comment by timo11** [comment]
I removed 'at least' from the localization for AppleJavaMinVersionError. There was nothing for MaxVersion. @maxxxxxdlp  did you localize that string for other langs?

**Comment by timo11** [comment]
Changed 'install' to 'install or run'

**Comment by maxxxxxdlp** [comment]
Changing Specify to russian via `user.properties` file did not change the language of the message - it still is in English

**Comment by norinespears** [comment]
I think this is a different issue but we discussed it yesterday in relation to this bug so I'm putting the detail in here. The count for Loan Return Preparations is not correct (or at least that is how I read the details) but resolved counts seem fine. Here are the actions:
1. Create a loan with quantity greater than one (fossil) and a second type (jar) with quantity greater than one for the same CO
2. return quantity 1 of one of the prep types - form (fossil) seems fine
3. return quantity 1 of the other prep type (jar) - form starts getting wonky:

<img width="1081" alt="Screen Shot 2020-04-14 at 8 17 55 AM" src="https://user-images.githubusercontent.com/61208178/79230466-4172f300-7e2a-11ea-9c84-4eaf365caa52.png">
although the other counts are perfectly fine, even the available quantities:
<img width="691" alt="Screen Shot 2020-04-14 at 8 18 12 AM" src="https://user-images.githubusercontent.com/61208178/79230532-5c456780-7e2a-11ea-84e2-70586e1818ce.png">

4. return another fossil: one of each prep type is added again:
<img width="1069" alt="Screen Shot 2020-04-14 at 8 19 26 AM" src="https://user-images.githubusercontent.com/61208178/79230684-97e03180-7e2a-11ea-967f-dd1ac2ced16a.png">
available counts are still good:
<img width="688" alt="Screen Shot 2020-04-14 at 8 19 32 AM" src="https://user-images.githubusercontent.com/61208178/79230736-aa5a6b00-7e2a-11ea-954b-468adde6c838.png">

**Comment by timo11** [comment]
This is not a problem with the getResolved and getResolvedQuantity fields. The problem is with the loan return process, which created 2 returns but did not update the LoanPreparation correctly. In the situation above it would probably be possible to return more items than were loaned, as Andy was able to do last Friday.

**Comment by norinespears** [comment]
Understood - what is the proper bug number for this information?

**Comment by timo11** [comment]
fields renamed to:
resolvedPreps: the number of loan preparations in the loan items view that are resolved
resolvedItems: the sum of resolved quantities of loan preparations.
