### ISSUE TITLE
SpWizard fails with `No value specified for parameter`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#742]
After setting up database options in SpWizard and before the database is fully built, I got the following exception

Happened on my Windows 10 machine (not inside a VM)
I have just installed Amazon Corretto 8 and MySQL 5.6.49 so the error may be connected to that

```
class_name: edu.ku.brc.specify.dbsupport.BuildFromGeonames
comments: 

stack_trace: 
java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2285)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2265)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at edu.ku.brc.specify.dbsupport.BuildFromGeonames.build(BuildFromGeonames.java:303)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createGeographyFromGeonames(BuildSampleDatabase.java:3870)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1070)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 75c66b90-b4c5-496c-2c16-17539b32de2d--171983321a0
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 90044672
user_name: m001p596
ip: 192.168.56.1
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1
```

**Comment by timo11** [comment]
Is there a line in the specify log that goes something like ERROR blah blah "adding country[Name][Code][Continent]?

**Comment by maxxxxxdlp** [comment]
Line 541:
```
12:35:27 ERROR specify.dbsupport.BuildFromGeonames:299 - Adding country[Angola][AO][AF]
```
[specify.log](https://github.com/specify/specify6/files/4505251/specify.log)

**Comment by maxxxxxdlp** [comment]
Happened again. Specify version is from 7 days ago. The database in on MariaDB (which is inside Docker)

Since the issue is persistent with another SQL server, I would suppose this is a problem with Specify rather than my SQL servers
