### ISSUE TITLE
MySQL error in SpWizard: Too many open files

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#782]
I have reinstalled macOS on my laptop
I have the newest MariaDB and Amazon Correto 8 installed
Pressing the `Create Specify Database` button throws the following exception

<img width="1440" alt="Screen Shot 2020-07-08 at 10 02 02 PM" src="https://user-images.githubusercontent.com/40512816/86959674-ed488800-c166-11ea-8f46-a6471e5a4fc2.png">

Clothing that exception window make the database creation process continue
Did we get a similar issue at any point before?

```
class_name: edu.ku.brc.specify.conversion.BasicSQLUtils
comments: 

stack_trace: 
java.sql.SQLException: Can't create table `specify`.`sgrbatchmatchresultitem` (errno: 24 "Too many open files")
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.update(BasicSQLUtils.java:1114)
	at edu.ku.brc.specify.dbsupport.SpecifySchemaUpdateService.createSGRTables(SpecifySchemaUpdateService.java:3231)
	at edu.ku.brc.specify.tools.SpecifySchemaGenerator.generateSchema(SpecifySchemaGenerator.java:151)
	at edu.ku.brc.specify.tools.SpecifySchemaGenerator.generateSchema(SpecifySchemaGenerator.java:74)
	at edu.ku.brc.specify.config.init.DatabasePanel$5.doInBackground(DatabasePanel.java:602)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 26c12cd3-aba9-c27e-3f3a-f311622fd14f--17306d23be0
os_name: Mac OS X
os_version: 10.15.5
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 467323376
user_name: mambo
ip: 127.0.0.1
app_version: 6.8.00

```

**Comment by maxxxxxdlp** [comment]
Also this:
```
java.sql.SQLException: Can't read dir of '.' (errno: 24 "Too many open files")
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.query(BasicSQLUtils.java:781)
	at edu.ku.brc.specify.conversion.BasicSQLUtils.query(BasicSQLUtils.java:734)
	at edu.ku.brc.dbsupport.MySQLDMBSUserMgr.doesDBExists(MySQLDMBSUserMgr.java:524)
	at edu.ku.brc.dbsupport.DBMSUserMgr.checkForDB(DBMSUserMgr.java:393)
	at edu.ku.brc.dbsupport.DBMSUserMgr.isOkToProceed(DBMSUserMgr.java:349)
	at edu.ku.brc.specify.config.init.DatabasePanel.isOkToProceed(DatabasePanel.java:968)
	at edu.ku.brc.specify.config.init.DatabasePanel.verifyDatabase(DatabasePanel.java:941)
	at edu.ku.brc.specify.config.init.DatabasePanel.createDB(DatabasePanel.java:496)
	at edu.ku.brc.specify.config.init.DatabasePanel$2.actionPerformed(DatabasePanel.java:296)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by grantfitzsimmons** [comment]
🤖:
> The error is happening because the program is attempting to create a table named `sgrbatchmatchresultitem` in the `specify` database using MySQL, but MySQL is reporting an error with the message "Too many open files" and the error number `errno: 24`. This error occurs when the operating system has reached its limit for the number of files it can have open at once, and the program is unable to open any more files. This could be caused by a variety of factors, such as a misconfiguration of the operating system or the program, or by the program attempting to open too many files at once.
