### ISSUE TITLE
Exceptions when using custom taxa files in the wizard

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#784]
I used my own webserver to test these files

Below, I will post a list of exceptions as well as the files I used in the process and the result of those errors

**Comment by maxxxxxdlp** [comment]
File:
old_truncated.xls and old_truncated_2.xls

Result:
Imported data till the first Genus

Exception:
class_name: edu.ku.brc.af.core.db.BackupServiceFactory
comments: 

stack_trace: 
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'Source' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1698)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createTaxonNode(BuildSampleDatabase.java:9533)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonNodes(BuildSampleDatabase.java:9472)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9318)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 19465d95-2bf4-272e-6d5b-0e1e4a20a65b--172c39b5320
os_name: Mac OS X
os_version: 10.15.5
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 404765704
user_name: mambo
ip: 10.42.0.205
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1

[Archive.zip](https://github.com/specify/specify6/files/4939756/Archive.zip)

**Comment by maxxxxxdlp** [comment]
File:
old_converted.xls

Result:
Did not import any data

Exception:
class_name: edu.ku.brc.af.core.db.BackupServiceFactory
comments: 

stack_trace: 
java.io.IOException: block[ 2 ] already removed
	at org.apache.poi.poifs.storage.BlockListImpl.remove(BlockListImpl.java:97)
	at org.apache.poi.poifs.storage.BlockAllocationTableReader.fetchBlocks(BlockAllocationTableReader.java:190)
	at org.apache.poi.poifs.storage.BlockListImpl.fetchBlocks(BlockListImpl.java:130)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.processProperties(POIFSFileSystem.java:530)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:176)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9211)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 19465d95-2bf4-272e-6d5b-0e1e4a20a65b--172c39b5320
os_name: Mac OS X
os_version: 10.15.5
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 177358456
user_name: mambo
ip: 10.42.0.205
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1
[old_converted.xls.zip](https://github.com/specify/specify6/files/4939757/old_converted.xls.zip)

**Comment by maxxxxxdlp** [comment]
I also used these files for testing

[Archive 2.zip](https://github.com/specify/specify6/files/4939758/Archive.2.zip)

**Comment by maxxxxxdlp** [comment]
All of these errors occurred after I selected the taxon file when the actual database build process was running
These are not the only exceptions I was getting
I guess all of my `xls` files had some problems that were causing these issues

**Comment by maxxxxxdlp** [comment]
And this is my modified `taxonfiles.xml`. Though I do not think that any of the errors I was getting are because of this file
[taxonfiles.xml.zip](https://github.com/specify/specify6/files/4939771/taxonfiles.xml.zip)

**Comment by timo11** [comment]
The first exception occurred because the wizard wasn't handling empty cells correctly.

A problem with the old_converted.xls file caused the second exception. I saved it as csv, then saved the csv as xls. The save to xls generated an error message that the file contained more rows than supported by xls and the excess rows were not being saved. The resulting xls file imports with no problems.
x-special/nautilus-clipboard
copy
file:///home/timo/maxtax/old_converted.xls/old_converted2.xls

**Comment by timo11** [comment]
[old_converted2.zip](https://github.com/specify/specify6/files/4960698/old_converted2.zip)

**Comment by maxxxxxdlp** [comment]
This time I did not get any exceptions, but the tree is empty
Also, tree descriptions are shown instead of tree names

<img width="1440" alt="Screen Shot 2020-07-24 at 2 41 11 PM" src="https://user-images.githubusercontent.com/40512816/88387855-1189a300-cdbc-11ea-9e1a-b12fb6116fa4.png">
<img width="1440" alt="Screen Shot 2020-07-24 at 2 41 24 PM" src="https://user-images.githubusercontent.com/40512816/88387869-15b5c080-cdbc-11ea-93d4-bed2b496ac43.png">
[glaucophyta.xls.zip](https://github.com/specify/specify6/files/4971751/glaucophyta.xls.zip)



Log files:
[specify.log](https://github.com/specify/specify6/files/4971747/specify.log)
[wizard.log](https://github.com/specify/specify6/files/4971748/wizard.log) (there was one exception due to 404 error on request for taxonfiles_2.xml, but that was the fault of my server)

**Comment by maxxxxxdlp** [comment]
@timo11 Is this bug still related to Wizard? Or should I create a separate issue
<img width="1440" alt="Screen Shot 2020-07-27 at 4 21 20 PM" src="https://user-images.githubusercontent.com/40512816/88546589-46e4f980-d025-11ea-8b59-a24e1fb74c08.png">

**Comment by timo11** [comment]
The selected taxon file was not being downloaded. Should work now. 
Still don't know what happens if a file has ranks that are not in the tree definition, or vice versa.

**Comment by maxxxxxdlp** [comment]
This is the exception when I try to upload a `.csv` file instead of `.xls`:
It should not be a problem if users don't have an option to upload an arbitrary file

```
class_name: edu.ku.brc.af.core.db.BackupServiceFactory
comments: 

stack_trace: 
java.io.IOException: block[ 2 ] already removed
	at org.apache.poi.poifs.storage.BlockListImpl.remove(BlockListImpl.java:97)
	at org.apache.poi.poifs.storage.BlockAllocationTableReader.fetchBlocks(BlockAllocationTableReader.java:190)
	at org.apache.poi.poifs.storage.BlockListImpl.fetchBlocks(BlockListImpl.java:130)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.processProperties(POIFSFileSystem.java:530)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:176)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9211)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 19465d95-2bf4-272e-6d5b-0e1e4a20a65b--1739b62fab0
os_name: Mac OS X
os_version: 10.15.5
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 307292128
user_name: mambo
ip: 10.42.0.205
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1

```

**Comment by maxxxxxdlp** [comment]
I tried `.xls` file, yet I am still getting the same exception:
[ITIS-30.07.2020-07_07_54.xls.zip](https://github.com/specify/specify6/files/4999832/ITIS-30.07.2020-07_07_54.xls.zip)

```
11:01:38 DEBUG specify.utilapps.BuildSampleDatabase:1026 -  fileName     [ITIS-30.07.2020-07_07_54.xls]
java.io.IOException: block[ 2 ] already removed
	at org.apache.poi.poifs.storage.BlockListImpl.remove(BlockListImpl.java:97)
	at org.apache.poi.poifs.storage.BlockAllocationTableReader.fetchBlocks(BlockAllocationTableReader.java:190)
	at org.apache.poi.poifs.storage.BlockListImpl.fetchBlocks(BlockListImpl.java:130)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.processProperties(POIFSFileSystem.java:530)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:176)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9211)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timo11** [comment]
I "solved" that problem before by saving the xls as csv (in libre office) then saving the csv as xls - which generated an error msg about there being too many rows to save as xls (blank rows?) which are being discarded. Then the new xls file worked. Whatever generated those xls files is doing something not quite right.

**Comment by maxxxxxdlp** [comment]
I am using an online converter for those, cause I don't have any software that supports `.xls`
Another reason to add `.xlsx` support in specify.

**Comment by maxxxxxdlp** [comment]
This file should not have worked cause it only has one column
It was accepted without any user-facing errors, though the tree is empty

<img width="1440" alt="Screen Shot 2020-07-31 at 6 57 34 PM" src="https://user-images.githubusercontent.com/40512816/89053318-b3326680-d35f-11ea-9163-edf3965ab588.png">

[ITIS31.07.2020-15_07_42.xls.zip](https://github.com/specify/specify6/files/5007877/ITIS31.07.2020-15_07_42.xls.zip)

**Comment by maxxxxxdlp** [comment]
Taxa tree is empty
[specify.log](https://github.com/specify/specify6/files/5007937/specify.log)
[wizard.log](https://github.com/specify/specify6/files/5007938/wizard.log)

[file2.xls.zip](https://github.com/specify/specify6/files/5007936/file2.xls.zip)

**Comment by maxxxxxdlp** [comment]
Taxa tree is empty
[file3.xls.zip](https://github.com/specify/specify6/files/5008003/file3.xls.zip)
[specify.log](https://github.com/specify/specify6/files/5008007/specify.log)
[wizard.log](https://github.com/specify/specify6/files/5008008/wizard.log)

**Comment by maxxxxxdlp** [comment]
I am still having trouble with this. The taxa tree is completely empty, besides the `Life` node

**Comment by timo11** [comment]
In file.xls the first row contains the name of the data set, not the column headers.
![Row1](https://user-images.githubusercontent.com/2915306/89573059-a4c8cc80-d7ef-11ea-9307-0c70f9670da4.png)

**Comment by maxxxxxdlp** [comment]
The problem was with Apple Numbers after all. It does not show header as part of the table in Apple Numbers. And I don't see an option to disable it when exporting.
<img width="1440" alt="Screen Shot 2020-08-06 at 10 12 26 PM" src="https://user-images.githubusercontent.com/40512816/89583269-57258180-d83a-11ea-8a41-78cbdabe0534.png">

I installed LibreOffice on my mac and created an `.XLS` out of `.CSV` using it. Everything worked fine and the tree was added to specify. Will do more testing tomorrow

**Comment by timo11** [comment]
FYI, file.xls worked when I deleted line 1 as shown in the LibreOffice screen shot above, that contains the ITIS download info.

**Comment by maxxxxxdlp** [comment]
Works fine with the entire tree of bacteria. Works regardless of whether subspecies is present in the tree definition or not

**Comment by maxxxxxdlp** [comment]
@beach53 should I write a script to generate the files for each phylum? Or would we do it closer to the release?

**Comment by maxxxxxdlp** [comment]
Changing the headings to mixed case from lower case does not cause problems

<img width="1264" alt="Screen Shot 2020-08-09 at 10 13 34 PM" src="https://user-images.githubusercontent.com/40512816/89739970-d6f75a00-da8d-11ea-8dca-724fe65dd6e6.png">

**Comment by maxxxxxdlp** [comment]
Adding more headings to the file caused exception:
[plantae_full.xls.zip](https://github.com/specify/specify6/files/5048268/plantae_full.xls.zip)

<img width="965" alt="Screen Shot 2020-08-09 at 10 22 07 PM" src="https://user-images.githubusercontent.com/40512816/89740134-e88d3180-da8e-11ea-8f20-63f1bd140d43.png">


```
class_name: edu.ku.brc.af.core.db.BackupServiceFactory
comments: 

stack_trace: 
java.lang.ArrayIndexOutOfBoundsException: 35
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9251)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 19465d95-2bf4-272e-6d5b-0e1e4a20a65b--1739b62fab0
os_name: Mac OS X
os_version: 10.15.6
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 409337984
user_name: mambo
ip: 192.168.1.11
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1

```

**Comment by maxxxxxdlp** [comment]
Having ranks below subspecies present does not seem to do anything. They are simply ignored

<img width="965" alt="Screen Shot 2020-08-09 at 10 37 17 PM" src="https://user-images.githubusercontent.com/40512816/89740435-4fabe580-da91-11ea-8289-f6b6b3a0dfe3.png">
<img width="1552" alt="Screen Shot 2020-08-09 at 10 39 59 PM" src="https://user-images.githubusercontent.com/40512816/89740436-50dd1280-da91-11ea-90a6-42869efda540.png">
<img width="1552" alt="Screen Shot 2020-08-09 at 10 40 10 PM" src="https://user-images.githubusercontent.com/40512816/89740438-5175a900-da91-11ea-9957-2f5ccb0fb760.png">

[all_plus_var_subvar.xls.zip](https://github.com/specify/specify6/files/5048283/all_plus_var_subvar.xls.zip)

**Comment by maxxxxxdlp** [comment]
Placing the same columns in the different order causes exception:

<img width="965" alt="Screen Shot 2020-08-09 at 10 45 08 PM" src="https://user-images.githubusercontent.com/40512816/89740534-17f16d80-da92-11ea-9649-d2732bc8b93b.png">
[all_after_subspe_ordered.xls.zip](https://github.com/specify/specify6/files/5048293/all_after_subspe_ordered.xls.zip)



```
class_name: edu.ku.brc.af.core.db.BackupServiceFactory
comments: 

stack_trace: 
java.lang.ArrayIndexOutOfBoundsException: 35
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.convertTaxonFromXLS(BuildSampleDatabase.java:9251)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDiscipline(BuildSampleDatabase.java:1029)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDisciplineAndCollection(BuildSampleDatabase.java:764)
	at edu.ku.brc.specify.utilapps.BuildSampleDatabase.createEmptyDivision(BuildSampleDatabase.java:711)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:1014)
	at edu.ku.brc.specify.config.init.SpecifyDBSetupWizard$4.doInBackground(SpecifyDBSetupWizard.java:954)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

task_name: 
title: 
id: 19465d95-2bf4-272e-6d5b-0e1e4a20a65b--1739b62fab0
os_name: Mac OS X
os_version: 10.15.6
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 278548864
user_name: mambo
ip: 192.168.1.11
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: 1
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: null
email: 1

```

**Comment by maxxxxxdlp** [comment]
Changing Phylum to Divison and vice versa does not seem to have any negative effect

**Comment by maxxxxxdlp** [comment]
Having all ranks be required but not included in the file does not cause any problems

<img width="1552" alt="Screen Shot 2020-08-09 at 10 59 22 PM" src="https://user-images.githubusercontent.com/40512816/89740784-8a634d00-da94-11ea-8c4d-3e81045f057e.png">
<img width="1552" alt="Screen Shot 2020-08-09 at 10 59 16 PM" src="https://user-images.githubusercontent.com/40512816/89740789-8e8f6a80-da94-11ea-9cba-6cc8b750e09d.png">

The column just gets added when needed

<img width="1552" alt="Screen Shot 2020-08-09 at 11 02 37 PM" src="https://user-images.githubusercontent.com/40512816/89740792-94854b80-da94-11ea-89e4-4a2619dac7f6.png">
<img width="1552" alt="Screen Shot 2020-08-09 at 11 03 02 PM" src="https://user-images.githubusercontent.com/40512816/89740795-98b16900-da94-11ea-8c80-ca4976544d24.png">

**Comment by maxxxxxdlp** [comment]
Closing this in favor of #805
