### ISSUE TITLE
Fix error associated with hidden barcode field

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#832]
In the test release (6.8.00_Edinburgh) the following error occurs when barcode field is hidden
class_name: edu.ku.brc.af.prefs.PrefsToolbar
comments:
stack_trace:
java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:620)
	at edu.ku.brc.specify.prefs.LoansPrefsPanel.addIdFldChoices(LoansPrefsPanel.java:180)
	at edu.ku.brc.specify.prefs.LoansPrefsPanel.createUI(LoansPrefsPanel.java:158)
	at edu.ku.brc.specify.prefs.LoansPrefsPanel.<init>(LoansPrefsPanel.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at edu.ku.brc.af.prefs.PrefsToolbar.loadSectionPrefs(PrefsToolbar.java:257)
	at edu.ku.brc.af.prefs.PrefsToolbar.init(PrefsToolbar.java:158)
	at edu.ku.brc.af.prefs.PrefsToolbar.<init>(PrefsToolbar.java:94)
	at edu.ku.brc.af.prefs.PreferencesDlg.initAsToolbar(PreferencesDlg.java:179)
	at edu.ku.brc.af.prefs.PreferencesDlg.<init>(PreferencesDlg.java:135)
	at edu.ku.brc.specify.Specify.doPreferences(Specify.java:867)
	at edu.ku.brc.specify.Specify$11.actionPerformed(Specify.java:1056)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
task_name: Startup
title:
id: f976b698-1604-8199-ff51-b3987e22e306--175dc036760
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_252
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 315428400
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00
collection: 1
discipline: Botany
division: m
institution: m
Collection_number: 1605815462.824
Discipline_number: 1605815462.4712
Division_number: 1605815460.3719
Institution_number: 1605812149.0096
email: m

**Comment by timo11** [comment]
I'm pretty sure that in order re-create the conditions for this bug all the following preparation fields need to be hidden: BarCode,GUID,SampleNumber,Text1,Text2,Text3,Text4,Text5,Text6,Text7,Text8, and Text9.
