### ISSUE TITLE
Error adding locality and paleo context sub form in CE

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#841]
When I save info in paleo context and locality subforms on collecting event I get an error. I'm able to save when paleo context and locality are on ce form as query comboboxes 

class_name: edu.ku.brc.af.ui.forms.FormViewObj
comments: 

stack_trace: 
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: edu.ku.brc.specify.datamodel.PaleoContext
	at org.hibernate.engine.ForeignKeys.getEntityIdentifierIfNotUnsaved(ForeignKeys.java:219)
	at org.hibernate.type.EntityType.getIdentifier(EntityType.java:397)
	at org.hibernate.type.EntityType.replace(EntityType.java:253)
	at org.hibernate.type.AbstractType.replace(AbstractType.java:153)
	at org.hibernate.type.TypeFactory.replace(TypeFactory.java:515)
	at org.hibernate.event.def.DefaultMergeEventListener.copyValues(DefaultMergeEventListener.java:377)
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:179)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2861)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3089)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:883)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

task_name: Data_Entry
title: 
id: f976b698-1604-8199-ff51-b3987e22e306--1725cd9b0f0
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_272
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 144645608
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00
collection: nq
discipline: Invertebrate Paleontology
division: m
institution: m
Collection_number: 1609874510.2804
Discipline_number: 1609874509.7128
Division_number: 1609874509.4399
Institution_number: 1609874507.3631
email: m

**Comment by timo11** [comment]
What values do IsPaleoContextEmbedded and PaleoContextChildTable have in the discipline's record in the discipline table?

**Comment by yvonneekanim** [comment]
> What values do IsPaleoContextEmbedded and PaleoContextChildTable have in the discipline's record in the discipline table?

1, collectingevent

**Comment by timo11** [comment]
What db is this happening for? Are there any existing shared paleocontext records? Does it happen for creates and edits?

**Comment by tlammer** [comment]
We both replicated it in new databases in both 6.8 and 6.7.04.  No existing pc records

**Comment by tlammer** [comment]
It only happens when ce is embedded on co and pc is embedded on ce.  No other configuration has the issue.
