### ISSUE TITLE
Storege Tree merges fail for nodes connected to preps via AlternateStorageID

### ISSUE THREAD

**Issue by timo11** [specify/specify6#848]
stack_trace:

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`specifymhn`.`preparation`, CONSTRAINT `FKB1982697EBDCBD14` FOREIGN KEY (`AlternateStorageID`) REFERENCES `storage` (`StorageID`))

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)

at com.mysql.jdbc.Util.getInstance(Util.java:372)

at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)

at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)

at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)

at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)

at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)

at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)

at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489)

at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:848)

at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742)

at edu.ku.brc.specify.treeutils.TreeMerger.mergeNodes(TreeMerger.java:223)

at edu.ku.brc.specify.treeutils.TreeMerger.mergeTreeIntoTree(TreeMerger.java:164)

at edu.ku.brc.specify.treeutils.TreeMerger.mergeTrees(TreeMerger.java:194)

at edu.ku.brc.specify.ui.treetables.TreeTableViewer$30.doInBackground(TreeTableViewer.java:2974)

at javax.swing.SwingWorker$1.call(SwingWorker.java:295)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at javax.swing.SwingWorker.run(SwingWorker.java:334)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

task_name: StorageTree

title:

id: c9145696-dd3d-1cea-fd08-55d6c278c152--1725cd9b0f0

os_name: Windows 10

os_version: 10.0

java_version: 1.8.0_275

java_vendor: Amazon.com Inc.

max_memory: 954728448

used_memory: 479251280

**Comment by maxxxxxdlp** [comment]
Seemed to work fine.

Log messages (does the last line suggest an error has occurred?):

```
20:31:46 DEBUG brc.ui.DragDropJList:304 - processing drop
20:31:46 DEBUG brc.ui.DragDropJList:322 - notifying callback that an acceptable drop occurred
20:31:46  WARN brc.ui.UIRegistry:533 - Couldn't find key[More info on Merge] in resource bundle [resources]
20:31:47  INFO ui.treetables.TreeTableViewer:2825 - merging Site(1) into 1(2)
20:31:47 DEBUG brc.ui.DragDropJList:132 - processing dragDropEnd notification
20:31:47 DEBUG brc.ui.DragDropJList:137 - Notifying callback that a DnD operation ended with success status false
```
