### ISSUE TITLE
Exchange Out causing error

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#888]
I'm on a Mac, Catalina, latest Deaccessions build
My interactions are created from the Barcode field in Preps
I have tested Exchange out with all 3 capabililities for adding preparations:
1. uncataloged
2. from Barcode
3. with a record set

Each time I try to save I get this error:
<img width="547" alt="Screen Shot 2021-04-28 at 7 23 21 PM" src="https://user-images.githubusercontent.com/61208178/116585489-15fc6280-a8de-11eb-8146-18c2c2520882.png">

**Comment by norinespears** [comment]
Not sure if this log file is helpful or not:
SELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstNameSELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstNameSELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstNameSELECT count(ag.agentId) FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
SELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstNameSELECT ag.lastName, ag.firstName, ag.middleInitial, ag.agentId FROM Agent ag WHERE ag.division.id = 2 AND  LOWER(ag.lastName) LIKE 'a%'  ORDER BY ag.lastName,ag.firstName
org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ExchangeOut.division
	at org.hibernate.engine.Nullability.checkNullability(Nullability.java:72)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:290)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)
	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)
	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)
	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.merge(HibernateDataProviderSession.java:220)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveToDB(FormViewObj.java:2861)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveObject(FormViewObj.java:3089)
	at edu.ku.brc.af.ui.forms.FormViewObj.saveOnThread(FormViewObj.java:2537)
	at edu.ku.brc.af.ui.forms.FormViewObj$8.actionPerformed(FormViewObj.java:883)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ok
okok

**Comment by norinespears** [comment]
or this:
11:27:01 ERROR forms.formatters.DataObjFieldFormatMgr:1122 - Couldn't find DataObjSwitchFormatter for class [edu.ku.brc.specify.datamodel.ExchangeOut]
11:27:01 DEBUG ui.forms.FormViewObj:5581 - shipments
11:27:01 DEBUG ui.forms.FormViewObj:5581 - addressOfRecord
11:27:01 DEBUG ui.forms.FormViewObj:5581 - shipments
11:27:01 DEBUG ui.forms.FormViewObj:5581 - addressOfRecord
11:27:01 DEBUG ui.forms.FormHelper:101 - updateLastEdittedInfo for [class edu.ku.brc.specify.datamodel.ExchangeOut]
11:27:01 DEBUG ui.forms.FormHelper:101 - updateLastEdittedInfo for [class edu.ku.brc.specify.datamodel.Shipment]
11:27:01 ERROR ui.forms.FormViewObj:3027 - ******* org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.ExchangeOut.division

**Comment by norinespears** [comment]
I'm on a Mac, Catalina, latest Deaccessions build #269
My interactions are created from the Barcode field in Preps

I no longer get the same error. I am now prompted to add items, can add the item but then when I am done the Exchange Out form does not appear.
