### ISSUE TITLE
BE gives error in paleo db

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#9]
When batch editing a query in a paleo db regardless of what table is being queried, the following error message occurs:

java.lang.NullPointerException
	at edu.ku.brc.specify.tasks.WorkbenchTask.getDataType(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.FormPane.createUIComp(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.FormPane.buildUI(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.FormPane.<init>(Unknown Source)
	at edu.ku.brc.specify.tasks.subpane.wb.WorkbenchPaneSS.<init>(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.doIt(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator.access$100(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(Unknown Source)
	at edu.ku.brc.specify.tasks.WorkbenchEditorCreator$1.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I used the 'demopaleo' db under demo databases in the specify 6 shared drive

**Comment by garrettgirard** [comment]
This appears to happen in both VP and IVP, I tested it in multiple databases as well.

**Comment by timo11** [comment]
I cannot duplicate this error. Even when I install the 20171218 build. Did you maybe run the update installer? Or choose to update an existing dir? Maybe if you installed to a new directory it would work.

**Comment by yvonneekanim** [comment]
I installed the 'nomercy' build to a new directory and the issue still occurs. BE seems to work for all other disciplines

**Comment by yvonneekanim** [comment]
Update: BE works with Ohio state paleo collection. The problem is probable isolated to KU & Florida paleo collections. Will do some more testing

**Comment by garrettgirard** [comment]
Well... I am still getting the error in cmnh. Maybe we should have Theresa or somebody test this too.

**Comment by yvonneekanim** [comment]
I'm still getting the error as well

**Comment by timo11** [comment]
I installed the Builtin build into a new directory (also a new directory for the launcher items) on the vm on the machine in the cube across from Yvonne and, using the DemoDatabase, couldn't reproduce the error, which was also happening this morning for the sample queries when logged in to the fish collection.

**Comment by garrettgirard** [comment]
Yvonne uninstalled all of the previous builds with the batch editor and removed their directories. She installed the latest build and is still getting the errors. After a lot of testing I have come to the conclusion that the discipline does not matter, and even within a single database the issue will occur sometimes, and other times it will work fine. It also does not matter what table you are querying/batch editing. My only guess at this point is that it has something to do with the specific records you are batch editing. I would recommend testing batch editing different results/records within the same query and see if one of them works every time and if others never work. Another thing I noticed was that if you get the error or no response from the BE button, the only way to get the batch editor to work again is to restart Specify. That might just be a coincidence though.
